export default eventHandler(async (event) => {
  const session = await useAuthSession(event);
  const body = await readBody(event);

  const {
    id,
    cleanup,
    cleanupCode,
    name,
    purchaseExpenseCategoryId,
    description,
    thankYouNote,
    refundPolicy,
    returnPolicy,
    companyPhone,
    commissionRate,
    image,
    email,
    printerLabelSize,
    companyId,
    companyType,
    companyName,
    storeUniqueName,
    isTaxIncluded,
    isAiImage,
    deliveryType,
    deliveryMode,
    fundDeliveryFees,
    deliveryRadius,
    deliveryFeesPerKm,
    waitingTime,
    waitingChargesPerMin,
    minDeliveryCharges,
    deliveryDiscountThreshold,
    deliveryDiscountAmount,
    isCostIncluded,
    isUserTrackIncluded,
    pointsValue,
    currency,
    role,
    pipelineId,
    address,
    openTime,
    closeTime,
    gstin,
    accHolderName,
    ifsc,
    accountNo,
    bankName,
    upiId,
    type,
    code,
    plan,
    logo,
    productInputs,
    variantInputs
  } = body;

  // Merge with existing session so user-specific fields (cleanup, cleanupCode, id, image, etc.)
  // are preserved when only company fields are being updated.
  await session.update({
    ...session.data,
    id,
    cleanup,
    cleanupCode,
    name,
    purchaseExpenseCategoryId,
    description,
    thankYouNote,
    refundPolicy,
    returnPolicy,
    companyPhone,
    commissionRate,
    image,
    email,
    printerLabelSize,
    companyId,
    companyType,
    companyName,
    storeUniqueName,
    isTaxIncluded,
    isAiImage,
    deliveryType,
    deliveryMode,
    fundDeliveryFees,
    deliveryRadius,
    deliveryFeesPerKm,
    waitingTime,
    waitingChargesPerMin,
    minDeliveryCharges,
    deliveryDiscountThreshold,
    deliveryDiscountAmount,
    isCostIncluded,
    isUserTrackIncluded,
    pointsValue,
    currency,
    role,
    pipelineId,
    address,
    openTime,
    closeTime,
    gstin,
    accHolderName,
    ifsc,
    accountNo,
    bankName,
    upiId,
    type,
    code,
    plan,
    logo,
    productInputs,
    variantInputs
  });
console.log("session",session.data)
  return session;
});
