steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'asia-south1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/markit',
        '--build-arg',
        'NUXT_UI_PRO_LICENSE=${_NUXT_UI_PRO_LICENSE}',
        '.'
      ]

images:
  - 'asia-south1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/markit'

substitutions:
  _NUXT_UI_PRO_LICENSE: projects/$PROJECT_ID/secrets/NUXT_UI_PRO_LICENSE/versions/latest
