import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {randomUUID} from 'node:crypto';
import {Pool} from 'pg';
import dotenv from 'dotenv';
dotenv.config({quiet:true});
const url=new URL(process.env.DATABASE_URL!);const schema=`money_test_${randomUUID().replaceAll('-','')}`;
const pool=new Pool({connectionString:process.env.DATABASE_URL});const c=await pool.connect();let db:any;
async function sql(s:string){await c.query('BEGIN');try{await c.query(`SET LOCAL search_path TO "${schema}"`);const r=await c.query(s);await c.query('COMMIT');return r;}catch(e){await c.query('ROLLBACK');throw e;}}
try{
 await c.query(`CREATE SCHEMA "${schema}"`);
 await sql(`CREATE TABLE companies(id text PRIMARY KEY,currency text DEFAULT 'INR');INSERT INTO companies(id) VALUES('a'),('b');
 CREATE TABLE clients(id text,name text);CREATE TABLE company_clients(company_id text,client_id text);
 CREATE TABLE company_users(company_id text,user_id text,name text,deleted boolean DEFAULT false);
 CREATE TABLE distributors(id text,name text);CREATE TABLE distributor_companies(company_id text,distributor_id text);
 INSERT INTO clients VALUES('customer','Customer'),('foreign','Other company');INSERT INTO company_clients VALUES('a','customer'),('b','foreign');
 INSERT INTO company_users(company_id,user_id,name) VALUES('a','staff','Staff');INSERT INTO distributors VALUES('vendor','Supplier');INSERT INTO distributor_companies VALUES('a','vendor');`);
 await sql(readFileSync(new URL('../prisma/migrations/20260926120000_accountant_v2/migration.sql',import.meta.url),'utf8'));
 await sql('ALTER TABLE accountant_v2_manual_journal_lines ADD COLUMN distributor_id text, ADD COLUMN source_parties jsonb');
 url.searchParams.set('schema',schema);url.searchParams.set('statement_cache_size','0');process.env.DATABASE_URL=url.toString();
 db=(await import('../server/prisma')).prisma;
 const {runAccountant}=await import('../server/utils/accountant/context');
 const {moneyRouter}=await import('../server/utils/accountant/money');
 const {accountingAccountRouter}=await import('../server/utils/accountant/accounts');
 const call=(router:any,method:string,path:string,body:any={},companyId='a',role='manager',query:any={})=>runAccountant({companyId,userId:'tester',role},async()=>{let result:any;const res={json(v:any){result=v;return res;},status(){return res;}};await router.dispatch(method,path,{user:{companyId,userId:'tester',role},body,query,params:{}},res);return result;});
 const options=await call(moneyRouter,'GET','/options');
 assert.equal(options.people.length,3);assert.ok(!options.people.some((p:any)=>p.id==='foreign'));
 const account=(type:string)=>options.accounts.find((a:any)=>a.accountType===type).id;
 const body={requestId:randomUUID(),direction:'RECEIVE',date:'2026-09-29',moneyAccountId:account('BANK'),purposeAccountId:account('ACCOUNTS_RECEIVABLE'),amount:100,party:{kind:'client',id:'customer'},reference:'TEST',note:'Collection'};
 const receipt=await call(moneyRouter,'POST','/',body);
 assert.equal(receipt.lines.find((l:any)=>l.accountId===body.moneyAccountId).side,'DEBIT');
 assert.equal(receipt.lines.find((l:any)=>l.accountId===body.purposeAccountId).side,'CREDIT');
 assert.equal(receipt.lines[0].sourceParties.client.id,'customer');
 assert.equal((await call(moneyRouter,'POST','/',body)).id,receipt.id,'Duplicate request is idempotent');
 await assert.rejects(call(moneyRouter,'POST','/',{...body,amount:101}));
 await assert.rejects(call(moneyRouter,'POST','/',{...body,requestId:randomUUID(),party:{kind:'client',id:'foreign'}}));
 await assert.rejects(call(moneyRouter,'POST','/',{...body,requestId:randomUUID(),party:null}));
 await assert.rejects(call(moneyRouter,'POST','/',{...body,requestId:randomUUID(),amount:1.001}));
 await assert.rejects(call(moneyRouter,'POST','/',{...body,requestId:randomUUID(),date:'2026-02-30'}));
 await assert.rejects(call(moneyRouter,'POST','/',{...body,requestId:randomUUID(),purposeAccountId:account('CASH')}));
 await assert.rejects(call(moneyRouter,'POST','/',body,'b'));
 await assert.rejects(call(moneyRouter,'GET','/options',{},'a','user'));
 const paid=await call(moneyRouter,'POST','/',{...body,requestId:randomUUID(),direction:'PAY',purposeAccountId:account('ACCOUNTS_PAYABLE'),party:{kind:'distributor',id:'vendor'}});
 assert.equal(paid.lines.find((l:any)=>l.accountId===body.moneyAccountId).side,'CREDIT');
 assert.ok(paid.lines.every((l:any)=>l.distributorId==='vendor'));
 const staffPayment=await call(moneyRouter,'POST','/',{...body,requestId:randomUUID(),direction:'PAY',purposeAccountId:account('EXPENSE'),party:{kind:'user',id:'staff'}});
 assert.equal(staffPayment.lines[0].sourceParties.user.id,'staff');
 const anonymous=await call(moneyRouter,'POST','/',{...body,requestId:randomUUID(),purposeAccountId:account('INCOME'),party:null,note:''});
 assert.equal(anonymous.lines[0].sourceParties,null,'General receipts may omit a person');
 await db.accountantAccountingAccount.update({where:{id:account('INCOME')},data:{isActive:false}});
 await assert.rejects(call(moneyRouter,'POST','/',{...body,requestId:randomUUID(),purposeAccountId:account('INCOME'),party:null}));
 const reversal=await call(moneyRouter,'POST',`/${receipt.id}/reverse`,{date:'2026-09-29'});
 assert.equal(reversal.reversedFromId,receipt.id);
 assert.equal((await call(moneyRouter,'POST',`/${receipt.id}/reverse`,{date:'2026-09-29'})).id,reversal.id);
 assert.equal((await call(moneyRouter,'GET','/')).data.find((r:any)=>r.id===receipt.id).reversals.length,1);
 const ledger=await call(accountingAccountRouter,'GET',`/${body.purposeAccountId}/ledger`);
 assert.equal(ledger.closingBalance,0,'Receipt plus reversal clears the receivable movement');

 const legacy=await call(moneyRouter,'POST','/',{...body,requestId:randomUUID(),purposeAccountId:account('EXPENSE'),party:null});
 await db.accountantManualJournal.update({where:{id:legacy.id},data:{sourceType:'LEGACY_CASH_BANK_HISTORY'}});
 assert.ok(!(await call(moneyRouter,'GET','/')).data.some((r:any)=>r.id===legacy.id),'Unadopted legacy journals are not generic money entries');
 await db.accountantAudit.create({data:{companyId:'a',userId:'tester',action:'imported',resource:'transaction-history-import',resourceId:'old-money-id',after:{journalId:legacy.id}}});
 assert.ok((await call(moneyRouter,'GET','/')).data.some((r:any)=>r.id===legacy.id),'Adopted historical row is visible');
 assert.ok(!(await call(moneyRouter,'GET','/',{},'b')).data.some((r:any)=>r.id===legacy.id),'Imported rows retain company scope');
 assert.equal((await call(moneyRouter,'POST',`/${legacy.id}/reverse`,{date:'2026-09-29'})).reversedFromId,legacy.id);
 await sql(`INSERT INTO accountant_v2_transaction_locks(id,company_id,module,lock_date,reason,is_locked,updated_at,locked_by_id) VALUES('lock','a','BANKING','2099-01-01','Closed',true,now(),'tester')`);
 await assert.rejects(call(moneyRouter,'POST','/',{...body,requestId:randomUUID()}));
 await assert.rejects(call(moneyRouter,'POST',`/${paid.id}/reverse`,{date:'2026-09-29'}));
 assert.equal((await sql(`SELECT journal_id FROM accountant_v2_manual_journal_lines GROUP BY journal_id HAVING sum(CASE side WHEN 'DEBIT' THEN amount ELSE -amount END)<>0`)).rowCount,0);
 console.log('Money page integration passed: receipt/payment, person links, supplier payable, idempotent retry/reversal, ledger totals, validation, locks, access and company isolation.');
}finally{await db?.$disconnect();await sql(`DROP SCHEMA "${schema}" CASCADE`);c.release();await pool.end();}
