import assert from 'node:assert/strict';
import {planHistory,cents,money} from '../scripts/lib/legacy-cash-bank-plan.mjs';
const targets={CASH:'cash',PRIMARY_BANK:'bank'};
const base={companyId:'a',targets,rows:[],native:{},imports:{},balances:{},offsetAccountId:'offset'};
const row=(type,id,account,direction,amount,date='2026-01-01 00:00:00')=>({source_type:type,source_id:id,account_type:account,direction,amount,date,note:'Historical receipt'});
const input={...base,rows:[row('OPENING','cash','CASH','CREDIT','10.01'),row('BILL','sale','CASH','CREDIT','100.00'),row('ACCOUNT_TRANSFER','transfer','CASH','DEBIT','40.00'),row('ACCOUNT_TRANSFER','transfer','PRIMARY_BANK','CREDIT','40.00')]};
const plan=planHistory(input);
assert.equal(plan.conflicts.length,0);assert.equal(plan.journals.length,3);
assert.deepEqual(plan.reconciliation.map(r=>r.newBalanceAfter),['70.01','40.00']);
assert.equal(plan.journals.find(j=>j.source==='ACCOUNT_TRANSFER:transfer').lines.length,2,'Transfer cash/bank legs are one journal with no offset');
assert.equal(plan.journals.find(j=>j.source==='BILL:sale').lines[0].side,'DEBIT','Old money received is a new asset debit');
for(const j of plan.journals)assert.equal(j.lines.reduce((a,l)=>a+cents(l.amount)*(l.side==='DEBIT'?1n:-1n),0n),0n);
const imports=Object.fromEntries(plan.journals.map(j=>[j.sourceId,{id:j.id,fingerprint:j.fingerprint,offsetAccountId:'offset',lines:j.lines.filter(l=>['cash','bank'].includes(l.account_id)),valid:true}]));
const repeat=planHistory({...input,imports,balances:{cash:'70.01',bank:'40.00'}});
assert.equal(repeat.journals.length,0);assert.equal(repeat.conflicts.length,0);
const changed=planHistory({...input,rows:[...input.rows.slice(1)],imports,balances:{cash:'70.01',bank:'40.00'}});
assert.ok(changed.conflicts.some(c=>c.reason.includes('absent')));
const native={id:'native',lines:[{account_id:'cash',date:input.rows[1].date,side:'DEBIT',amount:'100.00'}]};
const reused=planHistory({...base,rows:[input.rows[1]],native:{'BILL:sale':[native]},balances:{cash:'100.00'}});
assert.equal(reused.journals.length,0);assert.equal(reused.conflicts.length,0);assert.equal(reused.reused.length,1);
assert.ok(planHistory({...base,rows:[input.rows[1]],native:{'BILL:sale':[{...native,lines:[]}]}}).conflicts.length);
assert.ok(planHistory({...input,imports,native:{'BILL:sale':[native]},balances:{cash:'170.01',bank:'40.00'}}).conflicts.some(c=>c.reason.includes('both exist')));
const duplicated=planHistory({...base,rows:[input.rows[1],row('EXPENSE','linked','CASH','CREDIT','100.00')],native:{'BILL:sale':[native],'EXPENSE:linked':[native]},balances:{cash:'100.00'}});
assert.ok(duplicated.conflicts.some(c=>c.reason.includes('Two legacy')));
assert.equal(money(cents('9999999999999999.99')),'9999999999999999.99','No floating point loss');
assert.throws(()=>cents('1.001'));
console.log('Cash/bank planner passed: exact cents, direction mapping, opening/history/transfers, native reuse, repeat import, changed/deleted sources and duplicate-source conflicts.');
