ALTER TABLE companies
ADD COLUMN IF NOT EXISTS cod_charge DOUBLE PRECISION DEFAULT 0;

ALTER TABLE bills
ADD COLUMN IF NOT EXISTS cod_charge DOUBLE PRECISION DEFAULT 0;

ALTER TABLE ecomm_checkouts
ADD COLUMN IF NOT EXISTS cod_charge DOUBLE PRECISION NOT NULL DEFAULT 0;

ALTER TABLE ecomm_orders
ADD COLUMN IF NOT EXISTS cod_charge DOUBLE PRECISION NOT NULL DEFAULT 0;
