import { prisma } from '~/server/prisma'
import { writeFile } from 'node:fs/promises'
import { resolve } from 'node:path'

function memoryToMarkdown(content: Record<string, any>): string {
  const lines: string[] = [
    '# Storefront Memory',
    '',
    '_Auto-generated by the storefront editor. Edit via the Memory panel in `/storefront/editor`._',
    '',
  ]

  const theme = content.theme ?? {}
  lines.push('## Theme')
  for (const [k, v] of Object.entries(theme)) {
    if (v) lines.push(`- **${k}**: ${v}`)
  }
  lines.push('')

  const brand = content.brand ?? {}
  lines.push('## Brand')
  for (const [k, v] of Object.entries(brand)) {
    if (v) lines.push(`- **${k}**: ${v}`)
  }
  lines.push('')

  const pages = content.pages ?? {}
  if (Object.keys(pages).length) {
    lines.push('## Pages')
    for (const [slug, desc] of Object.entries(pages)) {
      lines.push(`- **${slug}**: ${desc}`)
    }
    lines.push('')
  }

  const sections = content.sections ?? {}
  if (Object.keys(sections).length) {
    lines.push('## Section Notes')
    for (const [type, note] of Object.entries(sections)) {
      lines.push(`- **${type}**: ${note}`)
    }
    lines.push('')
  }

  const ideas: string[] = content.ideas ?? []
  if (ideas.length) {
    lines.push('## Ideas')
    ideas.forEach((idea: string) => lines.push(`- ${idea}`))
    lines.push('')
  }

  if (content.architecture) {
    lines.push('## Architecture')
    lines.push(content.architecture)
    lines.push('')
  }

  if (content.notes) {
    lines.push('## Notes')
    lines.push(content.notes)
    lines.push('')
  }

  return lines.join('\n')
}

export default defineEventHandler(async (event) => {
  const session = await requireAuthSession(event)

  const body = await readBody(event)
  if (!body?.content || typeof body.content !== 'object') {
    throw createError({ statusCode: 400, message: 'content object required' })
  }

  await (prisma as any).storefrontMemory.upsert({
    where: { companyId: session.data.companyId },
    update: { content: body.content },
    create: { companyId: session.data.companyId, content: body.content },
  })

  // Mirror to markdown file for Claude Code access
  try {
    const mdPath = resolve(process.cwd(), 'docs/storefront-memory.md')
    await writeFile(mdPath, memoryToMarkdown(body.content), 'utf-8')
  } catch {
    // non-fatal — DB write succeeded
  }

  return { ok: true }
})
