/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import type { Prisma, BillHistory } from "@prisma/client";
import type { UseMutationOptions, UseQueryOptions, UseInfiniteQueryOptions, InfiniteData } from '@tanstack/vue-query';
import { getHooksContext } from '@zenstackhq/tanstack-query/runtime-v5/vue';
import type { MaybeRefOrGetter, ComputedRef, UnwrapRef } from 'vue';
import { useModelQuery, useInfiniteModelQuery, useModelMutation } from '@zenstackhq/tanstack-query/runtime-v5/vue';
import type { PickEnumerable, CheckSelect, QueryError, ExtraQueryOptions, ExtraMutationOptions } from '@zenstackhq/tanstack-query/runtime-v5';
import type { PolicyCrudKind } from '@zenstackhq/runtime'
import metadata from './__model_meta';
type DefaultError = QueryError;

export function useCreateBillHistory(options?: Omit<(MaybeRefOrGetter<UseMutationOptions<(BillHistory | undefined), DefaultError, Prisma.BillHistoryCreateArgs, unknown>> | ComputedRef<UseMutationOptions<(BillHistory | undefined), DefaultError, Prisma.BillHistoryCreateArgs, unknown>> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.BillHistoryCreateArgs, DefaultError, BillHistory, true>('BillHistory', 'POST', `${endpoint}/billHistory/create`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.BillHistoryCreateArgs>(
            args: Prisma.SelectSubset<T, Prisma.BillHistoryCreateArgs>,
            options?: Omit<(MaybeRefOrGetter<UseMutationOptions<(CheckSelect<T, BillHistory, Prisma.BillHistoryGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.BillHistoryCreateArgs>, unknown>> | ComputedRef<UseMutationOptions<(CheckSelect<T, BillHistory, Prisma.BillHistoryGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.BillHistoryCreateArgs>, unknown>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, BillHistory, Prisma.BillHistoryGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useCreateManyBillHistory(options?: Omit<(MaybeRefOrGetter<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.BillHistoryCreateManyArgs, unknown>> | ComputedRef<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.BillHistoryCreateManyArgs, unknown>> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.BillHistoryCreateManyArgs, DefaultError, Prisma.BatchPayload, false>('BillHistory', 'POST', `${endpoint}/billHistory/createMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.BillHistoryCreateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.BillHistoryCreateManyArgs>,
            options?: Omit<(MaybeRefOrGetter<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.BillHistoryCreateManyArgs>, unknown>> | ComputedRef<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.BillHistoryCreateManyArgs>, unknown>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useFindManyBillHistory<TArgs extends Prisma.BillHistoryFindManyArgs, TQueryFnData = Array<Prisma.BillHistoryGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: MaybeRefOrGetter<Prisma.SelectSubset<TArgs, Prisma.BillHistoryFindManyArgs>> | ComputedRef<Prisma.SelectSubset<TArgs, Prisma.BillHistoryFindManyArgs>>, options?: (MaybeRefOrGetter<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> | ComputedRef<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('BillHistory', `${endpoint}/billHistory/findMany`, args, options, fetch);
}

export function useInfiniteFindManyBillHistory<TArgs extends Prisma.BillHistoryFindManyArgs, TQueryFnData = Array<Prisma.BillHistoryGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: MaybeRefOrGetter<Prisma.SelectSubset<TArgs, Prisma.BillHistoryFindManyArgs>> | ComputedRef<Prisma.SelectSubset<TArgs, Prisma.BillHistoryFindManyArgs>>, options?: MaybeRefOrGetter<Omit<UseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>> | ComputedRef<Omit<UseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>>) {
    const { endpoint, fetch } = getHooksContext();
    return useInfiniteModelQuery<TQueryFnData, TData, TError>('BillHistory', `${endpoint}/billHistory/findMany`, args, options, fetch);
}

export function useFindUniqueBillHistory<TArgs extends Prisma.BillHistoryFindUniqueArgs, TQueryFnData = Prisma.BillHistoryGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: MaybeRefOrGetter<Prisma.SelectSubset<TArgs, Prisma.BillHistoryFindUniqueArgs>> | ComputedRef<Prisma.SelectSubset<TArgs, Prisma.BillHistoryFindUniqueArgs>>, options?: (MaybeRefOrGetter<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> | ComputedRef<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('BillHistory', `${endpoint}/billHistory/findUnique`, args, options, fetch);
}

export function useFindFirstBillHistory<TArgs extends Prisma.BillHistoryFindFirstArgs, TQueryFnData = Prisma.BillHistoryGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: MaybeRefOrGetter<Prisma.SelectSubset<TArgs, Prisma.BillHistoryFindFirstArgs>> | ComputedRef<Prisma.SelectSubset<TArgs, Prisma.BillHistoryFindFirstArgs>>, options?: (MaybeRefOrGetter<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> | ComputedRef<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('BillHistory', `${endpoint}/billHistory/findFirst`, args, options, fetch);
}

export function useUpdateBillHistory(options?: Omit<(MaybeRefOrGetter<UseMutationOptions<(BillHistory | undefined), DefaultError, Prisma.BillHistoryUpdateArgs, unknown>> | ComputedRef<UseMutationOptions<(BillHistory | undefined), DefaultError, Prisma.BillHistoryUpdateArgs, unknown>> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.BillHistoryUpdateArgs, DefaultError, BillHistory, true>('BillHistory', 'PUT', `${endpoint}/billHistory/update`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.BillHistoryUpdateArgs>(
            args: Prisma.SelectSubset<T, Prisma.BillHistoryUpdateArgs>,
            options?: Omit<(MaybeRefOrGetter<UseMutationOptions<(CheckSelect<T, BillHistory, Prisma.BillHistoryGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.BillHistoryUpdateArgs>, unknown>> | ComputedRef<UseMutationOptions<(CheckSelect<T, BillHistory, Prisma.BillHistoryGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.BillHistoryUpdateArgs>, unknown>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, BillHistory, Prisma.BillHistoryGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useUpdateManyBillHistory(options?: Omit<(MaybeRefOrGetter<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.BillHistoryUpdateManyArgs, unknown>> | ComputedRef<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.BillHistoryUpdateManyArgs, unknown>> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.BillHistoryUpdateManyArgs, DefaultError, Prisma.BatchPayload, false>('BillHistory', 'PUT', `${endpoint}/billHistory/updateMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.BillHistoryUpdateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.BillHistoryUpdateManyArgs>,
            options?: Omit<(MaybeRefOrGetter<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.BillHistoryUpdateManyArgs>, unknown>> | ComputedRef<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.BillHistoryUpdateManyArgs>, unknown>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useUpsertBillHistory(options?: Omit<(MaybeRefOrGetter<UseMutationOptions<(BillHistory | undefined), DefaultError, Prisma.BillHistoryUpsertArgs, unknown>> | ComputedRef<UseMutationOptions<(BillHistory | undefined), DefaultError, Prisma.BillHistoryUpsertArgs, unknown>> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.BillHistoryUpsertArgs, DefaultError, BillHistory, true>('BillHistory', 'POST', `${endpoint}/billHistory/upsert`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.BillHistoryUpsertArgs>(
            args: Prisma.SelectSubset<T, Prisma.BillHistoryUpsertArgs>,
            options?: Omit<(MaybeRefOrGetter<UseMutationOptions<(CheckSelect<T, BillHistory, Prisma.BillHistoryGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.BillHistoryUpsertArgs>, unknown>> | ComputedRef<UseMutationOptions<(CheckSelect<T, BillHistory, Prisma.BillHistoryGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.BillHistoryUpsertArgs>, unknown>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, BillHistory, Prisma.BillHistoryGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteBillHistory(options?: Omit<(MaybeRefOrGetter<UseMutationOptions<(BillHistory | undefined), DefaultError, Prisma.BillHistoryDeleteArgs, unknown>> | ComputedRef<UseMutationOptions<(BillHistory | undefined), DefaultError, Prisma.BillHistoryDeleteArgs, unknown>> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.BillHistoryDeleteArgs, DefaultError, BillHistory, true>('BillHistory', 'DELETE', `${endpoint}/billHistory/delete`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.BillHistoryDeleteArgs>(
            args: Prisma.SelectSubset<T, Prisma.BillHistoryDeleteArgs>,
            options?: Omit<(MaybeRefOrGetter<UseMutationOptions<(CheckSelect<T, BillHistory, Prisma.BillHistoryGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.BillHistoryDeleteArgs>, unknown>> | ComputedRef<UseMutationOptions<(CheckSelect<T, BillHistory, Prisma.BillHistoryGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.BillHistoryDeleteArgs>, unknown>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, BillHistory, Prisma.BillHistoryGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteManyBillHistory(options?: Omit<(MaybeRefOrGetter<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.BillHistoryDeleteManyArgs, unknown>> | ComputedRef<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.BillHistoryDeleteManyArgs, unknown>> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.BillHistoryDeleteManyArgs, DefaultError, Prisma.BatchPayload, false>('BillHistory', 'DELETE', `${endpoint}/billHistory/deleteMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.BillHistoryDeleteManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.BillHistoryDeleteManyArgs>,
            options?: Omit<(MaybeRefOrGetter<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.BillHistoryDeleteManyArgs>, unknown>> | ComputedRef<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.BillHistoryDeleteManyArgs>, unknown>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useAggregateBillHistory<TArgs extends Prisma.BillHistoryAggregateArgs, TQueryFnData = Prisma.GetBillHistoryAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: MaybeRefOrGetter<Prisma.SelectSubset<TArgs, Prisma.BillHistoryAggregateArgs>> | ComputedRef<Prisma.SelectSubset<TArgs, Prisma.BillHistoryAggregateArgs>>, options?: (MaybeRefOrGetter<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> | ComputedRef<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('BillHistory', `${endpoint}/billHistory/aggregate`, args, options, fetch);
}

export function useGroupByBillHistory<TArgs extends Prisma.BillHistoryGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.BillHistoryGroupByArgs['orderBy'] } : { orderBy?: Prisma.BillHistoryGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.BillHistoryGroupByOutputType, TArgs['by']> &
        {
            [P in ((keyof TArgs) & (keyof Prisma.BillHistoryGroupByOutputType))]: P extends '_count'
            ? TArgs[P] extends boolean
            ? number
            : Prisma.GetScalarType<TArgs[P], Prisma.BillHistoryGroupByOutputType[P]>
            : Prisma.GetScalarType<TArgs[P], Prisma.BillHistoryGroupByOutputType[P]>
        }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: MaybeRefOrGetter<Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.BillHistoryGroupByArgs, OrderByArg> & InputErrors>> | ComputedRef<Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.BillHistoryGroupByArgs, OrderByArg> & InputErrors>>, options?: (MaybeRefOrGetter<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> | ComputedRef<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('BillHistory', `${endpoint}/billHistory/groupBy`, args, options, fetch);
}

export function useCountBillHistory<TArgs extends Prisma.BillHistoryCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.BillHistoryCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: MaybeRefOrGetter<Prisma.SelectSubset<TArgs, Prisma.BillHistoryCountArgs>> | ComputedRef<Prisma.SelectSubset<TArgs, Prisma.BillHistoryCountArgs>>, options?: (MaybeRefOrGetter<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> | ComputedRef<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('BillHistory', `${endpoint}/billHistory/count`, args, options, fetch);
}

export function useCheckBillHistory<TError = DefaultError>(args: { operation: PolicyCrudKind; where?: { id?: string; operation?: string; billId?: string }; }, options?: (MaybeRefOrGetter<Omit<UnwrapRef<UseQueryOptions<boolean, TError, boolean>>, 'queryKey'>> | ComputedRef<Omit<UnwrapRef<UseQueryOptions<boolean, TError, boolean>>, 'queryKey'>> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<boolean, boolean, TError>('BillHistory', `${endpoint}/billHistory/check`, args, options, fetch);
}
