/******************************************************************************
* This file was generated by ZenStack CLI.
******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import type { Prisma, Company } from "@prisma/client";
import type { UseMutationOptions, UseQueryOptions, UseInfiniteQueryOptions, InfiniteData } from '@tanstack/vue-query';
import { getHooksContext } from '@zenstackhq/tanstack-query/runtime-v5/vue';
import type { MaybeRefOrGetter, ComputedRef, UnwrapRef } from 'vue';
import { useModelQuery, useInfiniteModelQuery, useModelMutation } from '@zenstackhq/tanstack-query/runtime-v5/vue';
import type { PickEnumerable, CheckSelect, QueryError, ExtraQueryOptions, ExtraMutationOptions } from '@zenstackhq/tanstack-query/runtime-v5';
import type { PolicyCrudKind } from '@zenstackhq/runtime'
import metadata from './__model_meta';
type DefaultError = QueryError;

export function useCreateCompany(options?: Omit<(MaybeRefOrGetter<UseMutationOptions<(Company | undefined), DefaultError, Prisma.CompanyCreateArgs, unknown>> | ComputedRef<UseMutationOptions<(Company | undefined), DefaultError, Prisma.CompanyCreateArgs, unknown>> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.CompanyCreateArgs, DefaultError, Company, true>('Company', 'POST', `${endpoint}/company/create`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.CompanyCreateArgs>(
            args: Prisma.SelectSubset<T, Prisma.CompanyCreateArgs>,
            options?: Omit<(MaybeRefOrGetter<UseMutationOptions<(CheckSelect<T, Company, Prisma.CompanyGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.CompanyCreateArgs>, unknown>> | ComputedRef<UseMutationOptions<(CheckSelect<T, Company, Prisma.CompanyGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.CompanyCreateArgs>, unknown>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, Company, Prisma.CompanyGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useCreateManyCompany(options?: Omit<(MaybeRefOrGetter<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.CompanyCreateManyArgs, unknown>> | ComputedRef<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.CompanyCreateManyArgs, unknown>> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.CompanyCreateManyArgs, DefaultError, Prisma.BatchPayload, false>('Company', 'POST', `${endpoint}/company/createMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.CompanyCreateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.CompanyCreateManyArgs>,
            options?: Omit<(MaybeRefOrGetter<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.CompanyCreateManyArgs>, unknown>> | ComputedRef<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.CompanyCreateManyArgs>, unknown>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useFindManyCompany<TArgs extends Prisma.CompanyFindManyArgs, TQueryFnData = Array<Prisma.CompanyGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: MaybeRefOrGetter<Prisma.SelectSubset<TArgs, Prisma.CompanyFindManyArgs>> | ComputedRef<Prisma.SelectSubset<TArgs, Prisma.CompanyFindManyArgs>>, options?: (MaybeRefOrGetter<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> | ComputedRef<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('Company', `${endpoint}/company/findMany`, args, options, fetch);
}

export function useInfiniteFindManyCompany<TArgs extends Prisma.CompanyFindManyArgs, TQueryFnData = Array<Prisma.CompanyGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: MaybeRefOrGetter<Prisma.SelectSubset<TArgs, Prisma.CompanyFindManyArgs>> | ComputedRef<Prisma.SelectSubset<TArgs, Prisma.CompanyFindManyArgs>>, options?: MaybeRefOrGetter<Omit<UseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>> | ComputedRef<Omit<UseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>>) {
    const { endpoint, fetch } = getHooksContext();
    return useInfiniteModelQuery<TQueryFnData, TData, TError>('Company', `${endpoint}/company/findMany`, args, options, fetch);
}

export function useFindUniqueCompany<TArgs extends Prisma.CompanyFindUniqueArgs, TQueryFnData = Prisma.CompanyGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: MaybeRefOrGetter<Prisma.SelectSubset<TArgs, Prisma.CompanyFindUniqueArgs>> | ComputedRef<Prisma.SelectSubset<TArgs, Prisma.CompanyFindUniqueArgs>>, options?: (MaybeRefOrGetter<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> | ComputedRef<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('Company', `${endpoint}/company/findUnique`, args, options, fetch);
}

export function useFindFirstCompany<TArgs extends Prisma.CompanyFindFirstArgs, TQueryFnData = Prisma.CompanyGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: MaybeRefOrGetter<Prisma.SelectSubset<TArgs, Prisma.CompanyFindFirstArgs>> | ComputedRef<Prisma.SelectSubset<TArgs, Prisma.CompanyFindFirstArgs>>, options?: (MaybeRefOrGetter<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> | ComputedRef<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('Company', `${endpoint}/company/findFirst`, args, options, fetch);
}

export function useUpdateCompany(options?: Omit<(MaybeRefOrGetter<UseMutationOptions<(Company | undefined), DefaultError, Prisma.CompanyUpdateArgs, unknown>> | ComputedRef<UseMutationOptions<(Company | undefined), DefaultError, Prisma.CompanyUpdateArgs, unknown>> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.CompanyUpdateArgs, DefaultError, Company, true>('Company', 'PUT', `${endpoint}/company/update`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.CompanyUpdateArgs>(
            args: Prisma.SelectSubset<T, Prisma.CompanyUpdateArgs>,
            options?: Omit<(MaybeRefOrGetter<UseMutationOptions<(CheckSelect<T, Company, Prisma.CompanyGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.CompanyUpdateArgs>, unknown>> | ComputedRef<UseMutationOptions<(CheckSelect<T, Company, Prisma.CompanyGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.CompanyUpdateArgs>, unknown>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, Company, Prisma.CompanyGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useUpdateManyCompany(options?: Omit<(MaybeRefOrGetter<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.CompanyUpdateManyArgs, unknown>> | ComputedRef<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.CompanyUpdateManyArgs, unknown>> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.CompanyUpdateManyArgs, DefaultError, Prisma.BatchPayload, false>('Company', 'PUT', `${endpoint}/company/updateMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.CompanyUpdateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.CompanyUpdateManyArgs>,
            options?: Omit<(MaybeRefOrGetter<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.CompanyUpdateManyArgs>, unknown>> | ComputedRef<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.CompanyUpdateManyArgs>, unknown>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useUpsertCompany(options?: Omit<(MaybeRefOrGetter<UseMutationOptions<(Company | undefined), DefaultError, Prisma.CompanyUpsertArgs, unknown>> | ComputedRef<UseMutationOptions<(Company | undefined), DefaultError, Prisma.CompanyUpsertArgs, unknown>> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.CompanyUpsertArgs, DefaultError, Company, true>('Company', 'POST', `${endpoint}/company/upsert`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.CompanyUpsertArgs>(
            args: Prisma.SelectSubset<T, Prisma.CompanyUpsertArgs>,
            options?: Omit<(MaybeRefOrGetter<UseMutationOptions<(CheckSelect<T, Company, Prisma.CompanyGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.CompanyUpsertArgs>, unknown>> | ComputedRef<UseMutationOptions<(CheckSelect<T, Company, Prisma.CompanyGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.CompanyUpsertArgs>, unknown>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, Company, Prisma.CompanyGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteCompany(options?: Omit<(MaybeRefOrGetter<UseMutationOptions<(Company | undefined), DefaultError, Prisma.CompanyDeleteArgs, unknown>> | ComputedRef<UseMutationOptions<(Company | undefined), DefaultError, Prisma.CompanyDeleteArgs, unknown>> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.CompanyDeleteArgs, DefaultError, Company, true>('Company', 'DELETE', `${endpoint}/company/delete`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.CompanyDeleteArgs>(
            args: Prisma.SelectSubset<T, Prisma.CompanyDeleteArgs>,
            options?: Omit<(MaybeRefOrGetter<UseMutationOptions<(CheckSelect<T, Company, Prisma.CompanyGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.CompanyDeleteArgs>, unknown>> | ComputedRef<UseMutationOptions<(CheckSelect<T, Company, Prisma.CompanyGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.CompanyDeleteArgs>, unknown>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, Company, Prisma.CompanyGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteManyCompany(options?: Omit<(MaybeRefOrGetter<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.CompanyDeleteManyArgs, unknown>> | ComputedRef<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.CompanyDeleteManyArgs, unknown>> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.CompanyDeleteManyArgs, DefaultError, Prisma.BatchPayload, false>('Company', 'DELETE', `${endpoint}/company/deleteMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.CompanyDeleteManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.CompanyDeleteManyArgs>,
            options?: Omit<(MaybeRefOrGetter<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.CompanyDeleteManyArgs>, unknown>> | ComputedRef<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.CompanyDeleteManyArgs>, unknown>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useAggregateCompany<TArgs extends Prisma.CompanyAggregateArgs, TQueryFnData = Prisma.GetCompanyAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: MaybeRefOrGetter<Prisma.SelectSubset<TArgs, Prisma.CompanyAggregateArgs>> | ComputedRef<Prisma.SelectSubset<TArgs, Prisma.CompanyAggregateArgs>>, options?: (MaybeRefOrGetter<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> | ComputedRef<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('Company', `${endpoint}/company/aggregate`, args, options, fetch);
}

export function useGroupByCompany<TArgs extends Prisma.CompanyGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.CompanyGroupByArgs['orderBy'] } : { orderBy?: Prisma.CompanyGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.CompanyGroupByOutputType, TArgs['by']> &
        {
            [P in ((keyof TArgs) & (keyof Prisma.CompanyGroupByOutputType))]: P extends '_count'
            ? TArgs[P] extends boolean
            ? number
            : Prisma.GetScalarType<TArgs[P], Prisma.CompanyGroupByOutputType[P]>
            : Prisma.GetScalarType<TArgs[P], Prisma.CompanyGroupByOutputType[P]>
        }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: MaybeRefOrGetter<Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.CompanyGroupByArgs, OrderByArg> & InputErrors>> | ComputedRef<Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.CompanyGroupByArgs, OrderByArg> & InputErrors>>, options?: (MaybeRefOrGetter<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> | ComputedRef<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('Company', `${endpoint}/company/groupBy`, args, options, fetch);
}

export function useCountCompany<TArgs extends Prisma.CompanyCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.CompanyCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: MaybeRefOrGetter<Prisma.SelectSubset<TArgs, Prisma.CompanyCountArgs>> | ComputedRef<Prisma.SelectSubset<TArgs, Prisma.CompanyCountArgs>>, options?: (MaybeRefOrGetter<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> | ComputedRef<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('Company', `${endpoint}/company/count`, args, options, fetch);
}
import type { CompanyType } from '@prisma/client';

export function useCheckCompany<TError = DefaultError>(args: { operation: PolicyCrudKind; where?: { id?: string; name?: string; storecode?: number; storeUniqueName?: string; logo?: string; description?: string; shopifyStoreName?: string; shopifyAccessToken?: string; tiktokCipher?: string; tiktokStoreName?: string; tiktokAccessToken?: string; tiktokAccessTokenExpireIn?: number; tiktokRefreshToken?: string; tiktokRefreshTokenExpireIn?: number; images?: string; isTaxIncluded?: boolean; status?: boolean; type?: CompanyType; accHolderName?: string; ifsc?: string; accountNo?: string; bankName?: string; gstin?: string; billCounter?: number }; }, options?: (MaybeRefOrGetter<Omit<UnwrapRef<UseQueryOptions<boolean, TError, boolean>>, 'queryKey'>> | ComputedRef<Omit<UnwrapRef<UseQueryOptions<boolean, TError, boolean>>, 'queryKey'>> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<boolean, boolean, TError>('Company', `${endpoint}/company/check`, args, options, fetch);
}
