/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import type { Prisma, DistributorCredit } from "@prisma/client";
import type { UseMutationOptions, UseQueryOptions, UseInfiniteQueryOptions, InfiniteData } from '@tanstack/vue-query';
import { getHooksContext } from '@zenstackhq/tanstack-query/runtime-v5/vue';
import type { MaybeRefOrGetter, ComputedRef, UnwrapRef } from 'vue';
import { useModelQuery, useInfiniteModelQuery, useModelMutation } from '@zenstackhq/tanstack-query/runtime-v5/vue';
import type { PickEnumerable, CheckSelect, QueryError, ExtraQueryOptions, ExtraMutationOptions } from '@zenstackhq/tanstack-query/runtime-v5';
import type { PolicyCrudKind } from '@zenstackhq/runtime'
import metadata from './__model_meta';
type DefaultError = QueryError;

export function useCreateDistributorCredit(options?: Omit<(MaybeRefOrGetter<UseMutationOptions<(DistributorCredit | undefined), DefaultError, Prisma.DistributorCreditCreateArgs, unknown>> | ComputedRef<UseMutationOptions<(DistributorCredit | undefined), DefaultError, Prisma.DistributorCreditCreateArgs, unknown>> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.DistributorCreditCreateArgs, DefaultError, DistributorCredit, true>('DistributorCredit', 'POST', `${endpoint}/distributorCredit/create`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.DistributorCreditCreateArgs>(
            args: Prisma.SelectSubset<T, Prisma.DistributorCreditCreateArgs>,
            options?: Omit<(MaybeRefOrGetter<UseMutationOptions<(CheckSelect<T, DistributorCredit, Prisma.DistributorCreditGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.DistributorCreditCreateArgs>, unknown>> | ComputedRef<UseMutationOptions<(CheckSelect<T, DistributorCredit, Prisma.DistributorCreditGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.DistributorCreditCreateArgs>, unknown>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, DistributorCredit, Prisma.DistributorCreditGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useCreateManyDistributorCredit(options?: Omit<(MaybeRefOrGetter<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.DistributorCreditCreateManyArgs, unknown>> | ComputedRef<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.DistributorCreditCreateManyArgs, unknown>> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.DistributorCreditCreateManyArgs, DefaultError, Prisma.BatchPayload, false>('DistributorCredit', 'POST', `${endpoint}/distributorCredit/createMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.DistributorCreditCreateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.DistributorCreditCreateManyArgs>,
            options?: Omit<(MaybeRefOrGetter<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.DistributorCreditCreateManyArgs>, unknown>> | ComputedRef<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.DistributorCreditCreateManyArgs>, unknown>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useFindManyDistributorCredit<TArgs extends Prisma.DistributorCreditFindManyArgs, TQueryFnData = Array<Prisma.DistributorCreditGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: MaybeRefOrGetter<Prisma.SelectSubset<TArgs, Prisma.DistributorCreditFindManyArgs>> | ComputedRef<Prisma.SelectSubset<TArgs, Prisma.DistributorCreditFindManyArgs>>, options?: (MaybeRefOrGetter<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> | ComputedRef<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('DistributorCredit', `${endpoint}/distributorCredit/findMany`, args, options, fetch);
}

export function useInfiniteFindManyDistributorCredit<TArgs extends Prisma.DistributorCreditFindManyArgs, TQueryFnData = Array<Prisma.DistributorCreditGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: MaybeRefOrGetter<Prisma.SelectSubset<TArgs, Prisma.DistributorCreditFindManyArgs>> | ComputedRef<Prisma.SelectSubset<TArgs, Prisma.DistributorCreditFindManyArgs>>, options?: MaybeRefOrGetter<Omit<UseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>> | ComputedRef<Omit<UseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>>) {
    const { endpoint, fetch } = getHooksContext();
    return useInfiniteModelQuery<TQueryFnData, TData, TError>('DistributorCredit', `${endpoint}/distributorCredit/findMany`, args, options, fetch);
}

export function useFindUniqueDistributorCredit<TArgs extends Prisma.DistributorCreditFindUniqueArgs, TQueryFnData = Prisma.DistributorCreditGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: MaybeRefOrGetter<Prisma.SelectSubset<TArgs, Prisma.DistributorCreditFindUniqueArgs>> | ComputedRef<Prisma.SelectSubset<TArgs, Prisma.DistributorCreditFindUniqueArgs>>, options?: (MaybeRefOrGetter<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> | ComputedRef<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('DistributorCredit', `${endpoint}/distributorCredit/findUnique`, args, options, fetch);
}

export function useFindFirstDistributorCredit<TArgs extends Prisma.DistributorCreditFindFirstArgs, TQueryFnData = Prisma.DistributorCreditGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: MaybeRefOrGetter<Prisma.SelectSubset<TArgs, Prisma.DistributorCreditFindFirstArgs>> | ComputedRef<Prisma.SelectSubset<TArgs, Prisma.DistributorCreditFindFirstArgs>>, options?: (MaybeRefOrGetter<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> | ComputedRef<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('DistributorCredit', `${endpoint}/distributorCredit/findFirst`, args, options, fetch);
}

export function useUpdateDistributorCredit(options?: Omit<(MaybeRefOrGetter<UseMutationOptions<(DistributorCredit | undefined), DefaultError, Prisma.DistributorCreditUpdateArgs, unknown>> | ComputedRef<UseMutationOptions<(DistributorCredit | undefined), DefaultError, Prisma.DistributorCreditUpdateArgs, unknown>> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.DistributorCreditUpdateArgs, DefaultError, DistributorCredit, true>('DistributorCredit', 'PUT', `${endpoint}/distributorCredit/update`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.DistributorCreditUpdateArgs>(
            args: Prisma.SelectSubset<T, Prisma.DistributorCreditUpdateArgs>,
            options?: Omit<(MaybeRefOrGetter<UseMutationOptions<(CheckSelect<T, DistributorCredit, Prisma.DistributorCreditGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.DistributorCreditUpdateArgs>, unknown>> | ComputedRef<UseMutationOptions<(CheckSelect<T, DistributorCredit, Prisma.DistributorCreditGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.DistributorCreditUpdateArgs>, unknown>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, DistributorCredit, Prisma.DistributorCreditGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useUpdateManyDistributorCredit(options?: Omit<(MaybeRefOrGetter<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.DistributorCreditUpdateManyArgs, unknown>> | ComputedRef<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.DistributorCreditUpdateManyArgs, unknown>> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.DistributorCreditUpdateManyArgs, DefaultError, Prisma.BatchPayload, false>('DistributorCredit', 'PUT', `${endpoint}/distributorCredit/updateMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.DistributorCreditUpdateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.DistributorCreditUpdateManyArgs>,
            options?: Omit<(MaybeRefOrGetter<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.DistributorCreditUpdateManyArgs>, unknown>> | ComputedRef<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.DistributorCreditUpdateManyArgs>, unknown>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useUpsertDistributorCredit(options?: Omit<(MaybeRefOrGetter<UseMutationOptions<(DistributorCredit | undefined), DefaultError, Prisma.DistributorCreditUpsertArgs, unknown>> | ComputedRef<UseMutationOptions<(DistributorCredit | undefined), DefaultError, Prisma.DistributorCreditUpsertArgs, unknown>> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.DistributorCreditUpsertArgs, DefaultError, DistributorCredit, true>('DistributorCredit', 'POST', `${endpoint}/distributorCredit/upsert`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.DistributorCreditUpsertArgs>(
            args: Prisma.SelectSubset<T, Prisma.DistributorCreditUpsertArgs>,
            options?: Omit<(MaybeRefOrGetter<UseMutationOptions<(CheckSelect<T, DistributorCredit, Prisma.DistributorCreditGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.DistributorCreditUpsertArgs>, unknown>> | ComputedRef<UseMutationOptions<(CheckSelect<T, DistributorCredit, Prisma.DistributorCreditGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.DistributorCreditUpsertArgs>, unknown>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, DistributorCredit, Prisma.DistributorCreditGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteDistributorCredit(options?: Omit<(MaybeRefOrGetter<UseMutationOptions<(DistributorCredit | undefined), DefaultError, Prisma.DistributorCreditDeleteArgs, unknown>> | ComputedRef<UseMutationOptions<(DistributorCredit | undefined), DefaultError, Prisma.DistributorCreditDeleteArgs, unknown>> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.DistributorCreditDeleteArgs, DefaultError, DistributorCredit, true>('DistributorCredit', 'DELETE', `${endpoint}/distributorCredit/delete`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.DistributorCreditDeleteArgs>(
            args: Prisma.SelectSubset<T, Prisma.DistributorCreditDeleteArgs>,
            options?: Omit<(MaybeRefOrGetter<UseMutationOptions<(CheckSelect<T, DistributorCredit, Prisma.DistributorCreditGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.DistributorCreditDeleteArgs>, unknown>> | ComputedRef<UseMutationOptions<(CheckSelect<T, DistributorCredit, Prisma.DistributorCreditGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.DistributorCreditDeleteArgs>, unknown>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, DistributorCredit, Prisma.DistributorCreditGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteManyDistributorCredit(options?: Omit<(MaybeRefOrGetter<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.DistributorCreditDeleteManyArgs, unknown>> | ComputedRef<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.DistributorCreditDeleteManyArgs, unknown>> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.DistributorCreditDeleteManyArgs, DefaultError, Prisma.BatchPayload, false>('DistributorCredit', 'DELETE', `${endpoint}/distributorCredit/deleteMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.DistributorCreditDeleteManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.DistributorCreditDeleteManyArgs>,
            options?: Omit<(MaybeRefOrGetter<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.DistributorCreditDeleteManyArgs>, unknown>> | ComputedRef<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.DistributorCreditDeleteManyArgs>, unknown>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useAggregateDistributorCredit<TArgs extends Prisma.DistributorCreditAggregateArgs, TQueryFnData = Prisma.GetDistributorCreditAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: MaybeRefOrGetter<Prisma.SelectSubset<TArgs, Prisma.DistributorCreditAggregateArgs>> | ComputedRef<Prisma.SelectSubset<TArgs, Prisma.DistributorCreditAggregateArgs>>, options?: (MaybeRefOrGetter<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> | ComputedRef<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('DistributorCredit', `${endpoint}/distributorCredit/aggregate`, args, options, fetch);
}

export function useGroupByDistributorCredit<TArgs extends Prisma.DistributorCreditGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.DistributorCreditGroupByArgs['orderBy'] } : { orderBy?: Prisma.DistributorCreditGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.DistributorCreditGroupByOutputType, TArgs['by']> &
        {
            [P in ((keyof TArgs) & (keyof Prisma.DistributorCreditGroupByOutputType))]: P extends '_count'
            ? TArgs[P] extends boolean
            ? number
            : Prisma.GetScalarType<TArgs[P], Prisma.DistributorCreditGroupByOutputType[P]>
            : Prisma.GetScalarType<TArgs[P], Prisma.DistributorCreditGroupByOutputType[P]>
        }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: MaybeRefOrGetter<Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.DistributorCreditGroupByArgs, OrderByArg> & InputErrors>> | ComputedRef<Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.DistributorCreditGroupByArgs, OrderByArg> & InputErrors>>, options?: (MaybeRefOrGetter<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> | ComputedRef<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('DistributorCredit', `${endpoint}/distributorCredit/groupBy`, args, options, fetch);
}

export function useCountDistributorCredit<TArgs extends Prisma.DistributorCreditCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.DistributorCreditCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: MaybeRefOrGetter<Prisma.SelectSubset<TArgs, Prisma.DistributorCreditCountArgs>> | ComputedRef<Prisma.SelectSubset<TArgs, Prisma.DistributorCreditCountArgs>>, options?: (MaybeRefOrGetter<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> | ComputedRef<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('DistributorCredit', `${endpoint}/distributorCredit/count`, args, options, fetch);
}

export function useCheckDistributorCredit<TError = DefaultError>(args: { operation: PolicyCrudKind; where?: { id?: string; remarks?: string; billNo?: string; distributorId?: string; companyId?: string }; }, options?: (MaybeRefOrGetter<Omit<UnwrapRef<UseQueryOptions<boolean, TError, boolean>>, 'queryKey'>> | ComputedRef<Omit<UnwrapRef<UseQueryOptions<boolean, TError, boolean>>, 'queryKey'>> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<boolean, boolean, TError>('DistributorCredit', `${endpoint}/distributorCredit/check`, args, options, fetch);
}
