/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import type { Prisma, LikeCompanyClient } from "@prisma/client";
import type { UseMutationOptions, UseQueryOptions, UseInfiniteQueryOptions, InfiniteData } from '@tanstack/vue-query';
import { getHooksContext } from '@zenstackhq/tanstack-query/runtime-v5/vue';
import type { MaybeRefOrGetter, ComputedRef, UnwrapRef } from 'vue';
import { useModelQuery, useInfiniteModelQuery, useModelMutation } from '@zenstackhq/tanstack-query/runtime-v5/vue';
import type { PickEnumerable, CheckSelect, QueryError, ExtraQueryOptions, ExtraMutationOptions } from '@zenstackhq/tanstack-query/runtime-v5';
import type { PolicyCrudKind } from '@zenstackhq/runtime'
import metadata from './__model_meta';
type DefaultError = QueryError;

export function useCreateLikeCompanyClient(options?: Omit<(MaybeRefOrGetter<UseMutationOptions<(LikeCompanyClient | undefined), DefaultError, Prisma.LikeCompanyClientCreateArgs, unknown>> | ComputedRef<UseMutationOptions<(LikeCompanyClient | undefined), DefaultError, Prisma.LikeCompanyClientCreateArgs, unknown>> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.LikeCompanyClientCreateArgs, DefaultError, LikeCompanyClient, true>('LikeCompanyClient', 'POST', `${endpoint}/likeCompanyClient/create`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.LikeCompanyClientCreateArgs>(
            args: Prisma.SelectSubset<T, Prisma.LikeCompanyClientCreateArgs>,
            options?: Omit<(MaybeRefOrGetter<UseMutationOptions<(CheckSelect<T, LikeCompanyClient, Prisma.LikeCompanyClientGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.LikeCompanyClientCreateArgs>, unknown>> | ComputedRef<UseMutationOptions<(CheckSelect<T, LikeCompanyClient, Prisma.LikeCompanyClientGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.LikeCompanyClientCreateArgs>, unknown>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, LikeCompanyClient, Prisma.LikeCompanyClientGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useCreateManyLikeCompanyClient(options?: Omit<(MaybeRefOrGetter<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.LikeCompanyClientCreateManyArgs, unknown>> | ComputedRef<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.LikeCompanyClientCreateManyArgs, unknown>> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.LikeCompanyClientCreateManyArgs, DefaultError, Prisma.BatchPayload, false>('LikeCompanyClient', 'POST', `${endpoint}/likeCompanyClient/createMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.LikeCompanyClientCreateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.LikeCompanyClientCreateManyArgs>,
            options?: Omit<(MaybeRefOrGetter<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.LikeCompanyClientCreateManyArgs>, unknown>> | ComputedRef<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.LikeCompanyClientCreateManyArgs>, unknown>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useFindManyLikeCompanyClient<TArgs extends Prisma.LikeCompanyClientFindManyArgs, TQueryFnData = Array<Prisma.LikeCompanyClientGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: MaybeRefOrGetter<Prisma.SelectSubset<TArgs, Prisma.LikeCompanyClientFindManyArgs>> | ComputedRef<Prisma.SelectSubset<TArgs, Prisma.LikeCompanyClientFindManyArgs>>, options?: (MaybeRefOrGetter<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> | ComputedRef<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('LikeCompanyClient', `${endpoint}/likeCompanyClient/findMany`, args, options, fetch);
}

export function useInfiniteFindManyLikeCompanyClient<TArgs extends Prisma.LikeCompanyClientFindManyArgs, TQueryFnData = Array<Prisma.LikeCompanyClientGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: MaybeRefOrGetter<Prisma.SelectSubset<TArgs, Prisma.LikeCompanyClientFindManyArgs>> | ComputedRef<Prisma.SelectSubset<TArgs, Prisma.LikeCompanyClientFindManyArgs>>, options?: MaybeRefOrGetter<Omit<UseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>> | ComputedRef<Omit<UseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>>) {
    const { endpoint, fetch } = getHooksContext();
    return useInfiniteModelQuery<TQueryFnData, TData, TError>('LikeCompanyClient', `${endpoint}/likeCompanyClient/findMany`, args, options, fetch);
}

export function useFindUniqueLikeCompanyClient<TArgs extends Prisma.LikeCompanyClientFindUniqueArgs, TQueryFnData = Prisma.LikeCompanyClientGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: MaybeRefOrGetter<Prisma.SelectSubset<TArgs, Prisma.LikeCompanyClientFindUniqueArgs>> | ComputedRef<Prisma.SelectSubset<TArgs, Prisma.LikeCompanyClientFindUniqueArgs>>, options?: (MaybeRefOrGetter<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> | ComputedRef<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('LikeCompanyClient', `${endpoint}/likeCompanyClient/findUnique`, args, options, fetch);
}

export function useFindFirstLikeCompanyClient<TArgs extends Prisma.LikeCompanyClientFindFirstArgs, TQueryFnData = Prisma.LikeCompanyClientGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: MaybeRefOrGetter<Prisma.SelectSubset<TArgs, Prisma.LikeCompanyClientFindFirstArgs>> | ComputedRef<Prisma.SelectSubset<TArgs, Prisma.LikeCompanyClientFindFirstArgs>>, options?: (MaybeRefOrGetter<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> | ComputedRef<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('LikeCompanyClient', `${endpoint}/likeCompanyClient/findFirst`, args, options, fetch);
}

export function useUpdateLikeCompanyClient(options?: Omit<(MaybeRefOrGetter<UseMutationOptions<(LikeCompanyClient | undefined), DefaultError, Prisma.LikeCompanyClientUpdateArgs, unknown>> | ComputedRef<UseMutationOptions<(LikeCompanyClient | undefined), DefaultError, Prisma.LikeCompanyClientUpdateArgs, unknown>> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.LikeCompanyClientUpdateArgs, DefaultError, LikeCompanyClient, true>('LikeCompanyClient', 'PUT', `${endpoint}/likeCompanyClient/update`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.LikeCompanyClientUpdateArgs>(
            args: Prisma.SelectSubset<T, Prisma.LikeCompanyClientUpdateArgs>,
            options?: Omit<(MaybeRefOrGetter<UseMutationOptions<(CheckSelect<T, LikeCompanyClient, Prisma.LikeCompanyClientGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.LikeCompanyClientUpdateArgs>, unknown>> | ComputedRef<UseMutationOptions<(CheckSelect<T, LikeCompanyClient, Prisma.LikeCompanyClientGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.LikeCompanyClientUpdateArgs>, unknown>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, LikeCompanyClient, Prisma.LikeCompanyClientGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useUpdateManyLikeCompanyClient(options?: Omit<(MaybeRefOrGetter<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.LikeCompanyClientUpdateManyArgs, unknown>> | ComputedRef<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.LikeCompanyClientUpdateManyArgs, unknown>> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.LikeCompanyClientUpdateManyArgs, DefaultError, Prisma.BatchPayload, false>('LikeCompanyClient', 'PUT', `${endpoint}/likeCompanyClient/updateMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.LikeCompanyClientUpdateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.LikeCompanyClientUpdateManyArgs>,
            options?: Omit<(MaybeRefOrGetter<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.LikeCompanyClientUpdateManyArgs>, unknown>> | ComputedRef<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.LikeCompanyClientUpdateManyArgs>, unknown>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useUpsertLikeCompanyClient(options?: Omit<(MaybeRefOrGetter<UseMutationOptions<(LikeCompanyClient | undefined), DefaultError, Prisma.LikeCompanyClientUpsertArgs, unknown>> | ComputedRef<UseMutationOptions<(LikeCompanyClient | undefined), DefaultError, Prisma.LikeCompanyClientUpsertArgs, unknown>> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.LikeCompanyClientUpsertArgs, DefaultError, LikeCompanyClient, true>('LikeCompanyClient', 'POST', `${endpoint}/likeCompanyClient/upsert`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.LikeCompanyClientUpsertArgs>(
            args: Prisma.SelectSubset<T, Prisma.LikeCompanyClientUpsertArgs>,
            options?: Omit<(MaybeRefOrGetter<UseMutationOptions<(CheckSelect<T, LikeCompanyClient, Prisma.LikeCompanyClientGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.LikeCompanyClientUpsertArgs>, unknown>> | ComputedRef<UseMutationOptions<(CheckSelect<T, LikeCompanyClient, Prisma.LikeCompanyClientGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.LikeCompanyClientUpsertArgs>, unknown>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, LikeCompanyClient, Prisma.LikeCompanyClientGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteLikeCompanyClient(options?: Omit<(MaybeRefOrGetter<UseMutationOptions<(LikeCompanyClient | undefined), DefaultError, Prisma.LikeCompanyClientDeleteArgs, unknown>> | ComputedRef<UseMutationOptions<(LikeCompanyClient | undefined), DefaultError, Prisma.LikeCompanyClientDeleteArgs, unknown>> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.LikeCompanyClientDeleteArgs, DefaultError, LikeCompanyClient, true>('LikeCompanyClient', 'DELETE', `${endpoint}/likeCompanyClient/delete`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.LikeCompanyClientDeleteArgs>(
            args: Prisma.SelectSubset<T, Prisma.LikeCompanyClientDeleteArgs>,
            options?: Omit<(MaybeRefOrGetter<UseMutationOptions<(CheckSelect<T, LikeCompanyClient, Prisma.LikeCompanyClientGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.LikeCompanyClientDeleteArgs>, unknown>> | ComputedRef<UseMutationOptions<(CheckSelect<T, LikeCompanyClient, Prisma.LikeCompanyClientGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.LikeCompanyClientDeleteArgs>, unknown>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, LikeCompanyClient, Prisma.LikeCompanyClientGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteManyLikeCompanyClient(options?: Omit<(MaybeRefOrGetter<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.LikeCompanyClientDeleteManyArgs, unknown>> | ComputedRef<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.LikeCompanyClientDeleteManyArgs, unknown>> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.LikeCompanyClientDeleteManyArgs, DefaultError, Prisma.BatchPayload, false>('LikeCompanyClient', 'DELETE', `${endpoint}/likeCompanyClient/deleteMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.LikeCompanyClientDeleteManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.LikeCompanyClientDeleteManyArgs>,
            options?: Omit<(MaybeRefOrGetter<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.LikeCompanyClientDeleteManyArgs>, unknown>> | ComputedRef<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.LikeCompanyClientDeleteManyArgs>, unknown>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useAggregateLikeCompanyClient<TArgs extends Prisma.LikeCompanyClientAggregateArgs, TQueryFnData = Prisma.GetLikeCompanyClientAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: MaybeRefOrGetter<Prisma.SelectSubset<TArgs, Prisma.LikeCompanyClientAggregateArgs>> | ComputedRef<Prisma.SelectSubset<TArgs, Prisma.LikeCompanyClientAggregateArgs>>, options?: (MaybeRefOrGetter<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> | ComputedRef<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('LikeCompanyClient', `${endpoint}/likeCompanyClient/aggregate`, args, options, fetch);
}

export function useGroupByLikeCompanyClient<TArgs extends Prisma.LikeCompanyClientGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.LikeCompanyClientGroupByArgs['orderBy'] } : { orderBy?: Prisma.LikeCompanyClientGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.LikeCompanyClientGroupByOutputType, TArgs['by']> &
        {
            [P in ((keyof TArgs) & (keyof Prisma.LikeCompanyClientGroupByOutputType))]: P extends '_count'
            ? TArgs[P] extends boolean
            ? number
            : Prisma.GetScalarType<TArgs[P], Prisma.LikeCompanyClientGroupByOutputType[P]>
            : Prisma.GetScalarType<TArgs[P], Prisma.LikeCompanyClientGroupByOutputType[P]>
        }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: MaybeRefOrGetter<Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.LikeCompanyClientGroupByArgs, OrderByArg> & InputErrors>> | ComputedRef<Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.LikeCompanyClientGroupByArgs, OrderByArg> & InputErrors>>, options?: (MaybeRefOrGetter<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> | ComputedRef<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('LikeCompanyClient', `${endpoint}/likeCompanyClient/groupBy`, args, options, fetch);
}

export function useCountLikeCompanyClient<TArgs extends Prisma.LikeCompanyClientCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.LikeCompanyClientCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: MaybeRefOrGetter<Prisma.SelectSubset<TArgs, Prisma.LikeCompanyClientCountArgs>> | ComputedRef<Prisma.SelectSubset<TArgs, Prisma.LikeCompanyClientCountArgs>>, options?: (MaybeRefOrGetter<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> | ComputedRef<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('LikeCompanyClient', `${endpoint}/likeCompanyClient/count`, args, options, fetch);
}

export function useCheckLikeCompanyClient<TError = DefaultError>(args: { operation: PolicyCrudKind; where?: { clientId?: string; companyId?: string; likeId?: string }; }, options?: (MaybeRefOrGetter<Omit<UnwrapRef<UseQueryOptions<boolean, TError, boolean>>, 'queryKey'>> | ComputedRef<Omit<UnwrapRef<UseQueryOptions<boolean, TError, boolean>>, 'queryKey'>> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<boolean, boolean, TError>('LikeCompanyClient', `${endpoint}/likeCompanyClient/check`, args, options, fetch);
}
