/******************************************************************************
* This file was generated by ZenStack CLI.
******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import type { Prisma, Notification } from "@prisma/client";
import type { UseMutationOptions, UseQueryOptions, UseInfiniteQueryOptions, InfiniteData } from '@tanstack/vue-query';
import { getHooksContext } from '@zenstackhq/tanstack-query/runtime-v5/vue';
import type { MaybeRefOrGetter, ComputedRef, UnwrapRef } from 'vue';
import { useModelQuery, useInfiniteModelQuery, useModelMutation } from '@zenstackhq/tanstack-query/runtime-v5/vue';
import type { PickEnumerable, CheckSelect, QueryError, ExtraQueryOptions, ExtraMutationOptions } from '@zenstackhq/tanstack-query/runtime-v5';
import type { PolicyCrudKind } from '@zenstackhq/runtime'
import metadata from './__model_meta';
type DefaultError = QueryError;

export function useCreateNotification(options?: Omit<(MaybeRefOrGetter<UseMutationOptions<(Notification | undefined), DefaultError, Prisma.NotificationCreateArgs, unknown>> | ComputedRef<UseMutationOptions<(Notification | undefined), DefaultError, Prisma.NotificationCreateArgs, unknown>> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.NotificationCreateArgs, DefaultError, Notification, true>('Notification', 'POST', `${endpoint}/notification/create`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.NotificationCreateArgs>(
            args: Prisma.SelectSubset<T, Prisma.NotificationCreateArgs>,
            options?: Omit<(MaybeRefOrGetter<UseMutationOptions<(CheckSelect<T, Notification, Prisma.NotificationGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.NotificationCreateArgs>, unknown>> | ComputedRef<UseMutationOptions<(CheckSelect<T, Notification, Prisma.NotificationGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.NotificationCreateArgs>, unknown>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, Notification, Prisma.NotificationGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useCreateManyNotification(options?: Omit<(MaybeRefOrGetter<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.NotificationCreateManyArgs, unknown>> | ComputedRef<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.NotificationCreateManyArgs, unknown>> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.NotificationCreateManyArgs, DefaultError, Prisma.BatchPayload, false>('Notification', 'POST', `${endpoint}/notification/createMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.NotificationCreateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.NotificationCreateManyArgs>,
            options?: Omit<(MaybeRefOrGetter<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.NotificationCreateManyArgs>, unknown>> | ComputedRef<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.NotificationCreateManyArgs>, unknown>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useFindManyNotification<TArgs extends Prisma.NotificationFindManyArgs, TQueryFnData = Array<Prisma.NotificationGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: MaybeRefOrGetter<Prisma.SelectSubset<TArgs, Prisma.NotificationFindManyArgs>> | ComputedRef<Prisma.SelectSubset<TArgs, Prisma.NotificationFindManyArgs>>, options?: (MaybeRefOrGetter<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> | ComputedRef<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('Notification', `${endpoint}/notification/findMany`, args, options, fetch);
}

export function useInfiniteFindManyNotification<TArgs extends Prisma.NotificationFindManyArgs, TQueryFnData = Array<Prisma.NotificationGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: MaybeRefOrGetter<Prisma.SelectSubset<TArgs, Prisma.NotificationFindManyArgs>> | ComputedRef<Prisma.SelectSubset<TArgs, Prisma.NotificationFindManyArgs>>, options?: MaybeRefOrGetter<Omit<UseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>> | ComputedRef<Omit<UseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>>) {
    const { endpoint, fetch } = getHooksContext();
    return useInfiniteModelQuery<TQueryFnData, TData, TError>('Notification', `${endpoint}/notification/findMany`, args, options, fetch);
}

export function useFindUniqueNotification<TArgs extends Prisma.NotificationFindUniqueArgs, TQueryFnData = Prisma.NotificationGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: MaybeRefOrGetter<Prisma.SelectSubset<TArgs, Prisma.NotificationFindUniqueArgs>> | ComputedRef<Prisma.SelectSubset<TArgs, Prisma.NotificationFindUniqueArgs>>, options?: (MaybeRefOrGetter<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> | ComputedRef<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('Notification', `${endpoint}/notification/findUnique`, args, options, fetch);
}

export function useFindFirstNotification<TArgs extends Prisma.NotificationFindFirstArgs, TQueryFnData = Prisma.NotificationGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: MaybeRefOrGetter<Prisma.SelectSubset<TArgs, Prisma.NotificationFindFirstArgs>> | ComputedRef<Prisma.SelectSubset<TArgs, Prisma.NotificationFindFirstArgs>>, options?: (MaybeRefOrGetter<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> | ComputedRef<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('Notification', `${endpoint}/notification/findFirst`, args, options, fetch);
}

export function useUpdateNotification(options?: Omit<(MaybeRefOrGetter<UseMutationOptions<(Notification | undefined), DefaultError, Prisma.NotificationUpdateArgs, unknown>> | ComputedRef<UseMutationOptions<(Notification | undefined), DefaultError, Prisma.NotificationUpdateArgs, unknown>> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.NotificationUpdateArgs, DefaultError, Notification, true>('Notification', 'PUT', `${endpoint}/notification/update`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.NotificationUpdateArgs>(
            args: Prisma.SelectSubset<T, Prisma.NotificationUpdateArgs>,
            options?: Omit<(MaybeRefOrGetter<UseMutationOptions<(CheckSelect<T, Notification, Prisma.NotificationGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.NotificationUpdateArgs>, unknown>> | ComputedRef<UseMutationOptions<(CheckSelect<T, Notification, Prisma.NotificationGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.NotificationUpdateArgs>, unknown>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, Notification, Prisma.NotificationGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useUpdateManyNotification(options?: Omit<(MaybeRefOrGetter<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.NotificationUpdateManyArgs, unknown>> | ComputedRef<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.NotificationUpdateManyArgs, unknown>> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.NotificationUpdateManyArgs, DefaultError, Prisma.BatchPayload, false>('Notification', 'PUT', `${endpoint}/notification/updateMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.NotificationUpdateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.NotificationUpdateManyArgs>,
            options?: Omit<(MaybeRefOrGetter<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.NotificationUpdateManyArgs>, unknown>> | ComputedRef<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.NotificationUpdateManyArgs>, unknown>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useUpsertNotification(options?: Omit<(MaybeRefOrGetter<UseMutationOptions<(Notification | undefined), DefaultError, Prisma.NotificationUpsertArgs, unknown>> | ComputedRef<UseMutationOptions<(Notification | undefined), DefaultError, Prisma.NotificationUpsertArgs, unknown>> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.NotificationUpsertArgs, DefaultError, Notification, true>('Notification', 'POST', `${endpoint}/notification/upsert`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.NotificationUpsertArgs>(
            args: Prisma.SelectSubset<T, Prisma.NotificationUpsertArgs>,
            options?: Omit<(MaybeRefOrGetter<UseMutationOptions<(CheckSelect<T, Notification, Prisma.NotificationGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.NotificationUpsertArgs>, unknown>> | ComputedRef<UseMutationOptions<(CheckSelect<T, Notification, Prisma.NotificationGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.NotificationUpsertArgs>, unknown>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, Notification, Prisma.NotificationGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteNotification(options?: Omit<(MaybeRefOrGetter<UseMutationOptions<(Notification | undefined), DefaultError, Prisma.NotificationDeleteArgs, unknown>> | ComputedRef<UseMutationOptions<(Notification | undefined), DefaultError, Prisma.NotificationDeleteArgs, unknown>> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.NotificationDeleteArgs, DefaultError, Notification, true>('Notification', 'DELETE', `${endpoint}/notification/delete`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.NotificationDeleteArgs>(
            args: Prisma.SelectSubset<T, Prisma.NotificationDeleteArgs>,
            options?: Omit<(MaybeRefOrGetter<UseMutationOptions<(CheckSelect<T, Notification, Prisma.NotificationGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.NotificationDeleteArgs>, unknown>> | ComputedRef<UseMutationOptions<(CheckSelect<T, Notification, Prisma.NotificationGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.NotificationDeleteArgs>, unknown>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, Notification, Prisma.NotificationGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteManyNotification(options?: Omit<(MaybeRefOrGetter<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.NotificationDeleteManyArgs, unknown>> | ComputedRef<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.NotificationDeleteManyArgs, unknown>> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.NotificationDeleteManyArgs, DefaultError, Prisma.BatchPayload, false>('Notification', 'DELETE', `${endpoint}/notification/deleteMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.NotificationDeleteManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.NotificationDeleteManyArgs>,
            options?: Omit<(MaybeRefOrGetter<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.NotificationDeleteManyArgs>, unknown>> | ComputedRef<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.NotificationDeleteManyArgs>, unknown>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useAggregateNotification<TArgs extends Prisma.NotificationAggregateArgs, TQueryFnData = Prisma.GetNotificationAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: MaybeRefOrGetter<Prisma.SelectSubset<TArgs, Prisma.NotificationAggregateArgs>> | ComputedRef<Prisma.SelectSubset<TArgs, Prisma.NotificationAggregateArgs>>, options?: (MaybeRefOrGetter<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> | ComputedRef<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('Notification', `${endpoint}/notification/aggregate`, args, options, fetch);
}

export function useGroupByNotification<TArgs extends Prisma.NotificationGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.NotificationGroupByArgs['orderBy'] } : { orderBy?: Prisma.NotificationGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.NotificationGroupByOutputType, TArgs['by']> &
        {
            [P in ((keyof TArgs) & (keyof Prisma.NotificationGroupByOutputType))]: P extends '_count'
            ? TArgs[P] extends boolean
            ? number
            : Prisma.GetScalarType<TArgs[P], Prisma.NotificationGroupByOutputType[P]>
            : Prisma.GetScalarType<TArgs[P], Prisma.NotificationGroupByOutputType[P]>
        }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: MaybeRefOrGetter<Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.NotificationGroupByArgs, OrderByArg> & InputErrors>> | ComputedRef<Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.NotificationGroupByArgs, OrderByArg> & InputErrors>>, options?: (MaybeRefOrGetter<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> | ComputedRef<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('Notification', `${endpoint}/notification/groupBy`, args, options, fetch);
}

export function useCountNotification<TArgs extends Prisma.NotificationCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.NotificationCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: MaybeRefOrGetter<Prisma.SelectSubset<TArgs, Prisma.NotificationCountArgs>> | ComputedRef<Prisma.SelectSubset<TArgs, Prisma.NotificationCountArgs>>, options?: (MaybeRefOrGetter<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> | ComputedRef<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('Notification', `${endpoint}/notification/count`, args, options, fetch);
}
import type { NotificationType } from '@prisma/client';

export function useCheckNotification<TError = DefaultError>(args: { operation: PolicyCrudKind; where?: { id?: string; companyId?: string; userId?: string; clientId?: string; type?: NotificationType; title?: string; message?: string; read?: boolean; actionPath?: string }; }, options?: (MaybeRefOrGetter<Omit<UnwrapRef<UseQueryOptions<boolean, TError, boolean>>, 'queryKey'>> | ComputedRef<Omit<UnwrapRef<UseQueryOptions<boolean, TError, boolean>>, 'queryKey'>> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<boolean, boolean, TError>('Notification', `${endpoint}/notification/check`, args, options, fetch);
}
