/******************************************************************************
* This file was generated by ZenStack CLI.
******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import type { Prisma, Payment } from "../../prisma/generated/client";
import type { UseMutationOptions, UseQueryOptions, UseInfiniteQueryOptions, InfiniteData } from '@tanstack/vue-query';
import { getHooksContext } from '@zenstackhq/tanstack-query/runtime-v5/vue';
import type { MaybeRefOrGetter, ComputedRef, UnwrapRef } from 'vue';
import { useModelQuery, useInfiniteModelQuery, useModelMutation } from '@zenstackhq/tanstack-query/runtime-v5/vue';
import type { PickEnumerable, CheckSelect, QueryError, ExtraQueryOptions, ExtraMutationOptions } from '@zenstackhq/tanstack-query/runtime-v5';
import type { PolicyCrudKind } from '@zenstackhq/runtime'
import metadata from './__model_meta';
type DefaultError = QueryError;

export function useCreatePayment(options?: Omit<(MaybeRefOrGetter<UseMutationOptions<(Payment | undefined), DefaultError, Prisma.PaymentCreateArgs, unknown>> | ComputedRef<UseMutationOptions<(Payment | undefined), DefaultError, Prisma.PaymentCreateArgs, unknown>> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.PaymentCreateArgs, DefaultError, Payment, true>('Payment', 'POST', `${endpoint}/payment/create`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.PaymentCreateArgs>(
            args: Prisma.SelectSubset<T, Prisma.PaymentCreateArgs>,
            options?: Omit<(MaybeRefOrGetter<UseMutationOptions<(CheckSelect<T, Payment, Prisma.PaymentGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.PaymentCreateArgs>, unknown>> | ComputedRef<UseMutationOptions<(CheckSelect<T, Payment, Prisma.PaymentGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.PaymentCreateArgs>, unknown>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, Payment, Prisma.PaymentGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useCreateManyPayment(options?: Omit<(MaybeRefOrGetter<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.PaymentCreateManyArgs, unknown>> | ComputedRef<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.PaymentCreateManyArgs, unknown>> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.PaymentCreateManyArgs, DefaultError, Prisma.BatchPayload, false>('Payment', 'POST', `${endpoint}/payment/createMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.PaymentCreateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.PaymentCreateManyArgs>,
            options?: Omit<(MaybeRefOrGetter<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.PaymentCreateManyArgs>, unknown>> | ComputedRef<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.PaymentCreateManyArgs>, unknown>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useFindManyPayment<TArgs extends Prisma.PaymentFindManyArgs, TQueryFnData = Array<Prisma.PaymentGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: MaybeRefOrGetter<Prisma.SelectSubset<TArgs, Prisma.PaymentFindManyArgs>> | ComputedRef<Prisma.SelectSubset<TArgs, Prisma.PaymentFindManyArgs>>, options?: (MaybeRefOrGetter<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> | ComputedRef<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('Payment', `${endpoint}/payment/findMany`, args, options, fetch);
}

export function useInfiniteFindManyPayment<TArgs extends Prisma.PaymentFindManyArgs, TQueryFnData = Array<Prisma.PaymentGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: MaybeRefOrGetter<Prisma.SelectSubset<TArgs, Prisma.PaymentFindManyArgs>> | ComputedRef<Prisma.SelectSubset<TArgs, Prisma.PaymentFindManyArgs>>, options?: MaybeRefOrGetter<Omit<UseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>> | ComputedRef<Omit<UseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>>) {
    const { endpoint, fetch } = getHooksContext();
    return useInfiniteModelQuery<TQueryFnData, TData, TError>('Payment', `${endpoint}/payment/findMany`, args, options, fetch);
}

export function useFindUniquePayment<TArgs extends Prisma.PaymentFindUniqueArgs, TQueryFnData = Prisma.PaymentGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: MaybeRefOrGetter<Prisma.SelectSubset<TArgs, Prisma.PaymentFindUniqueArgs>> | ComputedRef<Prisma.SelectSubset<TArgs, Prisma.PaymentFindUniqueArgs>>, options?: (MaybeRefOrGetter<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> | ComputedRef<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('Payment', `${endpoint}/payment/findUnique`, args, options, fetch);
}

export function useFindFirstPayment<TArgs extends Prisma.PaymentFindFirstArgs, TQueryFnData = Prisma.PaymentGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: MaybeRefOrGetter<Prisma.SelectSubset<TArgs, Prisma.PaymentFindFirstArgs>> | ComputedRef<Prisma.SelectSubset<TArgs, Prisma.PaymentFindFirstArgs>>, options?: (MaybeRefOrGetter<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> | ComputedRef<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('Payment', `${endpoint}/payment/findFirst`, args, options, fetch);
}

export function useUpdatePayment(options?: Omit<(MaybeRefOrGetter<UseMutationOptions<(Payment | undefined), DefaultError, Prisma.PaymentUpdateArgs, unknown>> | ComputedRef<UseMutationOptions<(Payment | undefined), DefaultError, Prisma.PaymentUpdateArgs, unknown>> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.PaymentUpdateArgs, DefaultError, Payment, true>('Payment', 'PUT', `${endpoint}/payment/update`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.PaymentUpdateArgs>(
            args: Prisma.SelectSubset<T, Prisma.PaymentUpdateArgs>,
            options?: Omit<(MaybeRefOrGetter<UseMutationOptions<(CheckSelect<T, Payment, Prisma.PaymentGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.PaymentUpdateArgs>, unknown>> | ComputedRef<UseMutationOptions<(CheckSelect<T, Payment, Prisma.PaymentGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.PaymentUpdateArgs>, unknown>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, Payment, Prisma.PaymentGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useUpdateManyPayment(options?: Omit<(MaybeRefOrGetter<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.PaymentUpdateManyArgs, unknown>> | ComputedRef<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.PaymentUpdateManyArgs, unknown>> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.PaymentUpdateManyArgs, DefaultError, Prisma.BatchPayload, false>('Payment', 'PUT', `${endpoint}/payment/updateMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.PaymentUpdateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.PaymentUpdateManyArgs>,
            options?: Omit<(MaybeRefOrGetter<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.PaymentUpdateManyArgs>, unknown>> | ComputedRef<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.PaymentUpdateManyArgs>, unknown>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useUpsertPayment(options?: Omit<(MaybeRefOrGetter<UseMutationOptions<(Payment | undefined), DefaultError, Prisma.PaymentUpsertArgs, unknown>> | ComputedRef<UseMutationOptions<(Payment | undefined), DefaultError, Prisma.PaymentUpsertArgs, unknown>> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.PaymentUpsertArgs, DefaultError, Payment, true>('Payment', 'POST', `${endpoint}/payment/upsert`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.PaymentUpsertArgs>(
            args: Prisma.SelectSubset<T, Prisma.PaymentUpsertArgs>,
            options?: Omit<(MaybeRefOrGetter<UseMutationOptions<(CheckSelect<T, Payment, Prisma.PaymentGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.PaymentUpsertArgs>, unknown>> | ComputedRef<UseMutationOptions<(CheckSelect<T, Payment, Prisma.PaymentGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.PaymentUpsertArgs>, unknown>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, Payment, Prisma.PaymentGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeletePayment(options?: Omit<(MaybeRefOrGetter<UseMutationOptions<(Payment | undefined), DefaultError, Prisma.PaymentDeleteArgs, unknown>> | ComputedRef<UseMutationOptions<(Payment | undefined), DefaultError, Prisma.PaymentDeleteArgs, unknown>> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.PaymentDeleteArgs, DefaultError, Payment, true>('Payment', 'DELETE', `${endpoint}/payment/delete`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.PaymentDeleteArgs>(
            args: Prisma.SelectSubset<T, Prisma.PaymentDeleteArgs>,
            options?: Omit<(MaybeRefOrGetter<UseMutationOptions<(CheckSelect<T, Payment, Prisma.PaymentGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.PaymentDeleteArgs>, unknown>> | ComputedRef<UseMutationOptions<(CheckSelect<T, Payment, Prisma.PaymentGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.PaymentDeleteArgs>, unknown>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, Payment, Prisma.PaymentGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteManyPayment(options?: Omit<(MaybeRefOrGetter<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.PaymentDeleteManyArgs, unknown>> | ComputedRef<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.PaymentDeleteManyArgs, unknown>> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.PaymentDeleteManyArgs, DefaultError, Prisma.BatchPayload, false>('Payment', 'DELETE', `${endpoint}/payment/deleteMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.PaymentDeleteManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.PaymentDeleteManyArgs>,
            options?: Omit<(MaybeRefOrGetter<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.PaymentDeleteManyArgs>, unknown>> | ComputedRef<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.PaymentDeleteManyArgs>, unknown>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useAggregatePayment<TArgs extends Prisma.PaymentAggregateArgs, TQueryFnData = Prisma.GetPaymentAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: MaybeRefOrGetter<Prisma.SelectSubset<TArgs, Prisma.PaymentAggregateArgs>> | ComputedRef<Prisma.SelectSubset<TArgs, Prisma.PaymentAggregateArgs>>, options?: (MaybeRefOrGetter<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> | ComputedRef<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('Payment', `${endpoint}/payment/aggregate`, args, options, fetch);
}

export function useGroupByPayment<TArgs extends Prisma.PaymentGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.PaymentGroupByArgs['orderBy'] } : { orderBy?: Prisma.PaymentGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.PaymentGroupByOutputType, TArgs['by']> &
        {
            [P in ((keyof TArgs) & (keyof Prisma.PaymentGroupByOutputType))]: P extends '_count'
            ? TArgs[P] extends boolean
            ? number
            : Prisma.GetScalarType<TArgs[P], Prisma.PaymentGroupByOutputType[P]>
            : Prisma.GetScalarType<TArgs[P], Prisma.PaymentGroupByOutputType[P]>
        }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: MaybeRefOrGetter<Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.PaymentGroupByArgs, OrderByArg> & InputErrors>> | ComputedRef<Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.PaymentGroupByArgs, OrderByArg> & InputErrors>>, options?: (MaybeRefOrGetter<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> | ComputedRef<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('Payment', `${endpoint}/payment/groupBy`, args, options, fetch);
}

export function useCountPayment<TArgs extends Prisma.PaymentCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.PaymentCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: MaybeRefOrGetter<Prisma.SelectSubset<TArgs, Prisma.PaymentCountArgs>> | ComputedRef<Prisma.SelectSubset<TArgs, Prisma.PaymentCountArgs>>, options?: (MaybeRefOrGetter<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> | ComputedRef<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('Payment', `${endpoint}/payment/count`, args, options, fetch);
}

export function useCheckPayment<TError = DefaultError>(args: { operation: PolicyCrudKind; where?: { id?: string; paymentMode?: string; paymentReference?: string; currency?: string; status?: string; companyId?: string }; }, options?: (MaybeRefOrGetter<Omit<UnwrapRef<UseQueryOptions<boolean, TError, boolean>>, 'queryKey'>> | ComputedRef<Omit<UnwrapRef<UseQueryOptions<boolean, TError, boolean>>, 'queryKey'>> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<boolean, boolean, TError>('Payment', `${endpoint}/payment/check`, args, options, fetch);
}
