/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import type { Prisma, Variantinput } from "@prisma/client";
import type { UseMutationOptions, UseQueryOptions, UseInfiniteQueryOptions, InfiniteData } from '@tanstack/vue-query';
import { getHooksContext } from '@zenstackhq/tanstack-query/runtime-v5/vue';
import type { MaybeRefOrGetter, ComputedRef, UnwrapRef } from 'vue';
import { useModelQuery, useInfiniteModelQuery, useModelMutation } from '@zenstackhq/tanstack-query/runtime-v5/vue';
import type { PickEnumerable, CheckSelect, QueryError, ExtraQueryOptions, ExtraMutationOptions } from '@zenstackhq/tanstack-query/runtime-v5';
import type { PolicyCrudKind } from '@zenstackhq/runtime'
import metadata from './__model_meta';
type DefaultError = QueryError;

export function useCreateVariantinput(options?: Omit<(MaybeRefOrGetter<UseMutationOptions<(Variantinput | undefined), DefaultError, Prisma.VariantinputCreateArgs, unknown>> | ComputedRef<UseMutationOptions<(Variantinput | undefined), DefaultError, Prisma.VariantinputCreateArgs, unknown>> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.VariantinputCreateArgs, DefaultError, Variantinput, true>('Variantinput', 'POST', `${endpoint}/variantinput/create`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.VariantinputCreateArgs>(
            args: Prisma.SelectSubset<T, Prisma.VariantinputCreateArgs>,
            options?: Omit<(MaybeRefOrGetter<UseMutationOptions<(CheckSelect<T, Variantinput, Prisma.VariantinputGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.VariantinputCreateArgs>, unknown>> | ComputedRef<UseMutationOptions<(CheckSelect<T, Variantinput, Prisma.VariantinputGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.VariantinputCreateArgs>, unknown>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, Variantinput, Prisma.VariantinputGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useCreateManyVariantinput(options?: Omit<(MaybeRefOrGetter<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.VariantinputCreateManyArgs, unknown>> | ComputedRef<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.VariantinputCreateManyArgs, unknown>> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.VariantinputCreateManyArgs, DefaultError, Prisma.BatchPayload, false>('Variantinput', 'POST', `${endpoint}/variantinput/createMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.VariantinputCreateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.VariantinputCreateManyArgs>,
            options?: Omit<(MaybeRefOrGetter<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.VariantinputCreateManyArgs>, unknown>> | ComputedRef<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.VariantinputCreateManyArgs>, unknown>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useFindManyVariantinput<TArgs extends Prisma.VariantinputFindManyArgs, TQueryFnData = Array<Prisma.VariantinputGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: MaybeRefOrGetter<Prisma.SelectSubset<TArgs, Prisma.VariantinputFindManyArgs>> | ComputedRef<Prisma.SelectSubset<TArgs, Prisma.VariantinputFindManyArgs>>, options?: (MaybeRefOrGetter<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> | ComputedRef<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('Variantinput', `${endpoint}/variantinput/findMany`, args, options, fetch);
}

export function useInfiniteFindManyVariantinput<TArgs extends Prisma.VariantinputFindManyArgs, TQueryFnData = Array<Prisma.VariantinputGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: MaybeRefOrGetter<Prisma.SelectSubset<TArgs, Prisma.VariantinputFindManyArgs>> | ComputedRef<Prisma.SelectSubset<TArgs, Prisma.VariantinputFindManyArgs>>, options?: MaybeRefOrGetter<Omit<UseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>> | ComputedRef<Omit<UseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>>) {
    const { endpoint, fetch } = getHooksContext();
    return useInfiniteModelQuery<TQueryFnData, TData, TError>('Variantinput', `${endpoint}/variantinput/findMany`, args, options, fetch);
}

export function useFindUniqueVariantinput<TArgs extends Prisma.VariantinputFindUniqueArgs, TQueryFnData = Prisma.VariantinputGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: MaybeRefOrGetter<Prisma.SelectSubset<TArgs, Prisma.VariantinputFindUniqueArgs>> | ComputedRef<Prisma.SelectSubset<TArgs, Prisma.VariantinputFindUniqueArgs>>, options?: (MaybeRefOrGetter<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> | ComputedRef<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('Variantinput', `${endpoint}/variantinput/findUnique`, args, options, fetch);
}

export function useFindFirstVariantinput<TArgs extends Prisma.VariantinputFindFirstArgs, TQueryFnData = Prisma.VariantinputGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: MaybeRefOrGetter<Prisma.SelectSubset<TArgs, Prisma.VariantinputFindFirstArgs>> | ComputedRef<Prisma.SelectSubset<TArgs, Prisma.VariantinputFindFirstArgs>>, options?: (MaybeRefOrGetter<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> | ComputedRef<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('Variantinput', `${endpoint}/variantinput/findFirst`, args, options, fetch);
}

export function useUpdateVariantinput(options?: Omit<(MaybeRefOrGetter<UseMutationOptions<(Variantinput | undefined), DefaultError, Prisma.VariantinputUpdateArgs, unknown>> | ComputedRef<UseMutationOptions<(Variantinput | undefined), DefaultError, Prisma.VariantinputUpdateArgs, unknown>> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.VariantinputUpdateArgs, DefaultError, Variantinput, true>('Variantinput', 'PUT', `${endpoint}/variantinput/update`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.VariantinputUpdateArgs>(
            args: Prisma.SelectSubset<T, Prisma.VariantinputUpdateArgs>,
            options?: Omit<(MaybeRefOrGetter<UseMutationOptions<(CheckSelect<T, Variantinput, Prisma.VariantinputGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.VariantinputUpdateArgs>, unknown>> | ComputedRef<UseMutationOptions<(CheckSelect<T, Variantinput, Prisma.VariantinputGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.VariantinputUpdateArgs>, unknown>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, Variantinput, Prisma.VariantinputGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useUpdateManyVariantinput(options?: Omit<(MaybeRefOrGetter<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.VariantinputUpdateManyArgs, unknown>> | ComputedRef<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.VariantinputUpdateManyArgs, unknown>> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.VariantinputUpdateManyArgs, DefaultError, Prisma.BatchPayload, false>('Variantinput', 'PUT', `${endpoint}/variantinput/updateMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.VariantinputUpdateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.VariantinputUpdateManyArgs>,
            options?: Omit<(MaybeRefOrGetter<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.VariantinputUpdateManyArgs>, unknown>> | ComputedRef<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.VariantinputUpdateManyArgs>, unknown>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useUpsertVariantinput(options?: Omit<(MaybeRefOrGetter<UseMutationOptions<(Variantinput | undefined), DefaultError, Prisma.VariantinputUpsertArgs, unknown>> | ComputedRef<UseMutationOptions<(Variantinput | undefined), DefaultError, Prisma.VariantinputUpsertArgs, unknown>> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.VariantinputUpsertArgs, DefaultError, Variantinput, true>('Variantinput', 'POST', `${endpoint}/variantinput/upsert`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.VariantinputUpsertArgs>(
            args: Prisma.SelectSubset<T, Prisma.VariantinputUpsertArgs>,
            options?: Omit<(MaybeRefOrGetter<UseMutationOptions<(CheckSelect<T, Variantinput, Prisma.VariantinputGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.VariantinputUpsertArgs>, unknown>> | ComputedRef<UseMutationOptions<(CheckSelect<T, Variantinput, Prisma.VariantinputGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.VariantinputUpsertArgs>, unknown>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, Variantinput, Prisma.VariantinputGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteVariantinput(options?: Omit<(MaybeRefOrGetter<UseMutationOptions<(Variantinput | undefined), DefaultError, Prisma.VariantinputDeleteArgs, unknown>> | ComputedRef<UseMutationOptions<(Variantinput | undefined), DefaultError, Prisma.VariantinputDeleteArgs, unknown>> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.VariantinputDeleteArgs, DefaultError, Variantinput, true>('Variantinput', 'DELETE', `${endpoint}/variantinput/delete`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.VariantinputDeleteArgs>(
            args: Prisma.SelectSubset<T, Prisma.VariantinputDeleteArgs>,
            options?: Omit<(MaybeRefOrGetter<UseMutationOptions<(CheckSelect<T, Variantinput, Prisma.VariantinputGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.VariantinputDeleteArgs>, unknown>> | ComputedRef<UseMutationOptions<(CheckSelect<T, Variantinput, Prisma.VariantinputGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.VariantinputDeleteArgs>, unknown>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, Variantinput, Prisma.VariantinputGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteManyVariantinput(options?: Omit<(MaybeRefOrGetter<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.VariantinputDeleteManyArgs, unknown>> | ComputedRef<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.VariantinputDeleteManyArgs, unknown>> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.VariantinputDeleteManyArgs, DefaultError, Prisma.BatchPayload, false>('Variantinput', 'DELETE', `${endpoint}/variantinput/deleteMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.VariantinputDeleteManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.VariantinputDeleteManyArgs>,
            options?: Omit<(MaybeRefOrGetter<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.VariantinputDeleteManyArgs>, unknown>> | ComputedRef<UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.VariantinputDeleteManyArgs>, unknown>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useAggregateVariantinput<TArgs extends Prisma.VariantinputAggregateArgs, TQueryFnData = Prisma.GetVariantinputAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: MaybeRefOrGetter<Prisma.SelectSubset<TArgs, Prisma.VariantinputAggregateArgs>> | ComputedRef<Prisma.SelectSubset<TArgs, Prisma.VariantinputAggregateArgs>>, options?: (MaybeRefOrGetter<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> | ComputedRef<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('Variantinput', `${endpoint}/variantinput/aggregate`, args, options, fetch);
}

export function useGroupByVariantinput<TArgs extends Prisma.VariantinputGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.VariantinputGroupByArgs['orderBy'] } : { orderBy?: Prisma.VariantinputGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.VariantinputGroupByOutputType, TArgs['by']> &
        {
            [P in ((keyof TArgs) & (keyof Prisma.VariantinputGroupByOutputType))]: P extends '_count'
            ? TArgs[P] extends boolean
            ? number
            : Prisma.GetScalarType<TArgs[P], Prisma.VariantinputGroupByOutputType[P]>
            : Prisma.GetScalarType<TArgs[P], Prisma.VariantinputGroupByOutputType[P]>
        }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: MaybeRefOrGetter<Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.VariantinputGroupByArgs, OrderByArg> & InputErrors>> | ComputedRef<Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.VariantinputGroupByArgs, OrderByArg> & InputErrors>>, options?: (MaybeRefOrGetter<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> | ComputedRef<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('Variantinput', `${endpoint}/variantinput/groupBy`, args, options, fetch);
}

export function useCountVariantinput<TArgs extends Prisma.VariantinputCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.VariantinputCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: MaybeRefOrGetter<Prisma.SelectSubset<TArgs, Prisma.VariantinputCountArgs>> | ComputedRef<Prisma.SelectSubset<TArgs, Prisma.VariantinputCountArgs>>, options?: (MaybeRefOrGetter<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> | ComputedRef<Omit<UnwrapRef<UseQueryOptions<TQueryFnData, TError, TData>>, 'queryKey'>> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('Variantinput', `${endpoint}/variantinput/count`, args, options, fetch);
}

export function useCheckVariantinput<TError = DefaultError>(args: { operation: PolicyCrudKind; where?: { id?: string; name?: boolean; code?: boolean; sprice?: boolean; pprice?: boolean; dprice?: boolean; discount?: boolean; qty?: boolean; sizes?: boolean; images?: boolean; companyId?: string }; }, options?: (MaybeRefOrGetter<Omit<UnwrapRef<UseQueryOptions<boolean, TError, boolean>>, 'queryKey'>> | ComputedRef<Omit<UnwrapRef<UseQueryOptions<boolean, TError, boolean>>, 'queryKey'>> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<boolean, boolean, TError>('Variantinput', `${endpoint}/variantinput/check`, args, options, fetch);
}
