version: "3.3"
name: "electric_quickstart"

services:
  electric:
    image: electricsql/electric
    environment:
      DATABASE_URL: postgresql://postgres:reez@host.docker.internal:5432/bazaar
      ELECTRIC_INSECURE: true
    ports:
      - "5133:3000"
