import { z } from 'zod';
/**
 * `Company` schema excluding foreign keys and relations.
 */
export declare const CompanyScalarSchema: z.ZodObject<{
    id: z.ZodString;
    name: z.ZodString;
    storecode: z.ZodNumber;
    storeUniqueName: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    logo: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    description: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    shopifyStoreName: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    shopifyAccessToken: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    tiktokCipher: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    tiktokStoreName: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    tiktokAccessToken: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    tiktokAccessTokenExpireIn: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    tiktokRefreshToken: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    tiktokRefreshTokenExpireIn: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    images: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    isTaxIncluded: z.ZodDefault<z.ZodBoolean>;
    status: z.ZodDefault<z.ZodBoolean>;
    type: z.ZodEnum<["seller", "buyer"]>;
    accHolderName: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    ifsc: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    accountNo: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    bankName: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    gstin: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    upiId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    billCounter: z.ZodDefault<z.ZodNumber>;
    barcodeCounter: z.ZodDefault<z.ZodNumber>;
}, "strict", z.ZodTypeAny, {
    id: string;
    name: string;
    storecode: number;
    isTaxIncluded: boolean;
    status: boolean;
    type: "seller" | "buyer";
    billCounter: number;
    barcodeCounter: number;
    storeUniqueName?: string | null | undefined;
    logo?: string | null | undefined;
    description?: string | null | undefined;
    shopifyStoreName?: string | null | undefined;
    shopifyAccessToken?: string | null | undefined;
    tiktokCipher?: string | null | undefined;
    tiktokStoreName?: string | null | undefined;
    tiktokAccessToken?: string | null | undefined;
    tiktokAccessTokenExpireIn?: number | null | undefined;
    tiktokRefreshToken?: string | null | undefined;
    tiktokRefreshTokenExpireIn?: number | null | undefined;
    images?: string | null | undefined;
    accHolderName?: string | null | undefined;
    ifsc?: string | null | undefined;
    accountNo?: string | null | undefined;
    bankName?: string | null | undefined;
    gstin?: string | null | undefined;
    upiId?: string | null | undefined;
}, {
    id: string;
    name: string;
    storecode: number;
    type: "seller" | "buyer";
    storeUniqueName?: string | null | undefined;
    logo?: string | null | undefined;
    description?: string | null | undefined;
    shopifyStoreName?: string | null | undefined;
    shopifyAccessToken?: string | null | undefined;
    tiktokCipher?: string | null | undefined;
    tiktokStoreName?: string | null | undefined;
    tiktokAccessToken?: string | null | undefined;
    tiktokAccessTokenExpireIn?: number | null | undefined;
    tiktokRefreshToken?: string | null | undefined;
    tiktokRefreshTokenExpireIn?: number | null | undefined;
    images?: string | null | undefined;
    isTaxIncluded?: boolean | undefined;
    status?: boolean | undefined;
    accHolderName?: string | null | undefined;
    ifsc?: string | null | undefined;
    accountNo?: string | null | undefined;
    bankName?: string | null | undefined;
    gstin?: string | null | undefined;
    upiId?: string | null | undefined;
    billCounter?: number | undefined;
    barcodeCounter?: number | undefined;
}>;
/**
 * `Company` schema including all fields (scalar, foreign key, and relations) and validations.
 */
export declare const CompanySchema: z.ZodObject<{
    id: z.ZodString;
    name: z.ZodString;
    storecode: z.ZodNumber;
    storeUniqueName: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    logo: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    description: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    shopifyStoreName: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    shopifyAccessToken: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    tiktokCipher: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    tiktokStoreName: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    tiktokAccessToken: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    tiktokAccessTokenExpireIn: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    tiktokRefreshToken: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    tiktokRefreshTokenExpireIn: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    images: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    isTaxIncluded: z.ZodDefault<z.ZodBoolean>;
    status: z.ZodDefault<z.ZodBoolean>;
    type: z.ZodEnum<["seller", "buyer"]>;
    accHolderName: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    ifsc: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    accountNo: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    bankName: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    gstin: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    upiId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    billCounter: z.ZodDefault<z.ZodNumber>;
    barcodeCounter: z.ZodDefault<z.ZodNumber>;
} & {
    users: z.ZodOptional<z.ZodOptional<z.ZodArray<z.ZodUnknown, "many">>>;
    clients: z.ZodOptional<z.ZodOptional<z.ZodArray<z.ZodUnknown, "many">>>;
    products: z.ZodOptional<z.ZodOptional<z.ZodArray<z.ZodUnknown, "many">>>;
    categories: z.ZodOptional<z.ZodOptional<z.ZodArray<z.ZodUnknown, "many">>>;
    subcategories: z.ZodOptional<z.ZodOptional<z.ZodArray<z.ZodUnknown, "many">>>;
    bills: z.ZodOptional<z.ZodOptional<z.ZodArray<z.ZodUnknown, "many">>>;
    tokenbills: z.ZodOptional<z.ZodOptional<z.ZodArray<z.ZodUnknown, "many">>>;
    accounts: z.ZodOptional<z.ZodOptional<z.ZodArray<z.ZodUnknown, "many">>>;
    expenseCategories: z.ZodOptional<z.ZodOptional<z.ZodArray<z.ZodUnknown, "many">>>;
    expenses: z.ZodOptional<z.ZodOptional<z.ZodArray<z.ZodUnknown, "many">>>;
    payment: z.ZodOptional<z.ZodOptional<z.ZodArray<z.ZodUnknown, "many">>>;
    variants: z.ZodOptional<z.ZodOptional<z.ZodArray<z.ZodUnknown, "many">>>;
    purchaseOrders: z.ZodOptional<z.ZodOptional<z.ZodArray<z.ZodUnknown, "many">>>;
    items: z.ZodOptional<z.ZodOptional<z.ZodArray<z.ZodUnknown, "many">>>;
    pipeline: z.ZodOptional<z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnknown>>>;
    notifications: z.ZodOptional<z.ZodOptional<z.ZodArray<z.ZodUnknown, "many">>>;
    address: z.ZodOptional<z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnknown>>>;
    distributor: z.ZodOptional<z.ZodOptional<z.ZodArray<z.ZodUnknown, "many">>>;
}, "strip", z.ZodTypeAny, {
    id: string;
    name: string;
    storecode: number;
    isTaxIncluded: boolean;
    status: boolean;
    type: "seller" | "buyer";
    billCounter: number;
    barcodeCounter: number;
    storeUniqueName?: string | null | undefined;
    logo?: string | null | undefined;
    description?: string | null | undefined;
    shopifyStoreName?: string | null | undefined;
    shopifyAccessToken?: string | null | undefined;
    tiktokCipher?: string | null | undefined;
    tiktokStoreName?: string | null | undefined;
    tiktokAccessToken?: string | null | undefined;
    tiktokAccessTokenExpireIn?: number | null | undefined;
    tiktokRefreshToken?: string | null | undefined;
    tiktokRefreshTokenExpireIn?: number | null | undefined;
    images?: string | null | undefined;
    users?: unknown[] | undefined;
    clients?: unknown[] | undefined;
    products?: unknown[] | undefined;
    categories?: unknown[] | undefined;
    subcategories?: unknown[] | undefined;
    bills?: unknown[] | undefined;
    tokenbills?: unknown[] | undefined;
    accounts?: unknown[] | undefined;
    expenseCategories?: unknown[] | undefined;
    expenses?: unknown[] | undefined;
    payment?: unknown[] | undefined;
    variants?: unknown[] | undefined;
    purchaseOrders?: unknown[] | undefined;
    items?: unknown[] | undefined;
    pipeline?: Record<string, unknown> | undefined;
    accHolderName?: string | null | undefined;
    ifsc?: string | null | undefined;
    accountNo?: string | null | undefined;
    bankName?: string | null | undefined;
    gstin?: string | null | undefined;
    upiId?: string | null | undefined;
    notifications?: unknown[] | undefined;
    address?: Record<string, unknown> | undefined;
    distributor?: unknown[] | undefined;
}, {
    id: string;
    name: string;
    storecode: number;
    type: "seller" | "buyer";
    storeUniqueName?: string | null | undefined;
    logo?: string | null | undefined;
    description?: string | null | undefined;
    shopifyStoreName?: string | null | undefined;
    shopifyAccessToken?: string | null | undefined;
    tiktokCipher?: string | null | undefined;
    tiktokStoreName?: string | null | undefined;
    tiktokAccessToken?: string | null | undefined;
    tiktokAccessTokenExpireIn?: number | null | undefined;
    tiktokRefreshToken?: string | null | undefined;
    tiktokRefreshTokenExpireIn?: number | null | undefined;
    images?: string | null | undefined;
    isTaxIncluded?: boolean | undefined;
    users?: unknown[] | undefined;
    clients?: unknown[] | undefined;
    products?: unknown[] | undefined;
    categories?: unknown[] | undefined;
    subcategories?: unknown[] | undefined;
    bills?: unknown[] | undefined;
    tokenbills?: unknown[] | undefined;
    accounts?: unknown[] | undefined;
    expenseCategories?: unknown[] | undefined;
    expenses?: unknown[] | undefined;
    payment?: unknown[] | undefined;
    variants?: unknown[] | undefined;
    purchaseOrders?: unknown[] | undefined;
    items?: unknown[] | undefined;
    status?: boolean | undefined;
    pipeline?: Record<string, unknown> | undefined;
    accHolderName?: string | null | undefined;
    ifsc?: string | null | undefined;
    accountNo?: string | null | undefined;
    bankName?: string | null | undefined;
    gstin?: string | null | undefined;
    upiId?: string | null | undefined;
    notifications?: unknown[] | undefined;
    address?: Record<string, unknown> | undefined;
    distributor?: unknown[] | undefined;
    billCounter?: number | undefined;
    barcodeCounter?: number | undefined;
}>;
/**
 * Schema used for validating Prisma create input. For internal use only.
 * @private
 */
export declare const CompanyPrismaCreateSchema: z.ZodObject<{
    id: z.ZodOptional<z.ZodString>;
    name: z.ZodOptional<z.ZodString>;
    storecode: z.ZodOptional<z.ZodNumber>;
    storeUniqueName: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    logo: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    description: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    shopifyStoreName: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    shopifyAccessToken: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    tiktokCipher: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    tiktokStoreName: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    tiktokAccessToken: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    tiktokAccessTokenExpireIn: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodNumber>>>;
    tiktokRefreshToken: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    tiktokRefreshTokenExpireIn: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodNumber>>>;
    images: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    isTaxIncluded: z.ZodOptional<z.ZodDefault<z.ZodBoolean>>;
    status: z.ZodOptional<z.ZodDefault<z.ZodBoolean>>;
    type: z.ZodOptional<z.ZodEnum<["seller", "buyer"]>>;
    accHolderName: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    ifsc: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    accountNo: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    bankName: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    gstin: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    upiId: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    billCounter: z.ZodOptional<z.ZodDefault<z.ZodNumber>>;
    barcodeCounter: z.ZodOptional<z.ZodDefault<z.ZodNumber>>;
}, "passthrough", z.ZodTypeAny, z.objectOutputType<{
    id: z.ZodOptional<z.ZodString>;
    name: z.ZodOptional<z.ZodString>;
    storecode: z.ZodOptional<z.ZodNumber>;
    storeUniqueName: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    logo: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    description: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    shopifyStoreName: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    shopifyAccessToken: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    tiktokCipher: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    tiktokStoreName: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    tiktokAccessToken: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    tiktokAccessTokenExpireIn: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodNumber>>>;
    tiktokRefreshToken: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    tiktokRefreshTokenExpireIn: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodNumber>>>;
    images: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    isTaxIncluded: z.ZodOptional<z.ZodDefault<z.ZodBoolean>>;
    status: z.ZodOptional<z.ZodDefault<z.ZodBoolean>>;
    type: z.ZodOptional<z.ZodEnum<["seller", "buyer"]>>;
    accHolderName: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    ifsc: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    accountNo: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    bankName: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    gstin: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    upiId: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    billCounter: z.ZodOptional<z.ZodDefault<z.ZodNumber>>;
    barcodeCounter: z.ZodOptional<z.ZodDefault<z.ZodNumber>>;
}, z.ZodTypeAny, "passthrough">, z.objectInputType<{
    id: z.ZodOptional<z.ZodString>;
    name: z.ZodOptional<z.ZodString>;
    storecode: z.ZodOptional<z.ZodNumber>;
    storeUniqueName: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    logo: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    description: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    shopifyStoreName: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    shopifyAccessToken: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    tiktokCipher: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    tiktokStoreName: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    tiktokAccessToken: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    tiktokAccessTokenExpireIn: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodNumber>>>;
    tiktokRefreshToken: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    tiktokRefreshTokenExpireIn: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodNumber>>>;
    images: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    isTaxIncluded: z.ZodOptional<z.ZodDefault<z.ZodBoolean>>;
    status: z.ZodOptional<z.ZodDefault<z.ZodBoolean>>;
    type: z.ZodOptional<z.ZodEnum<["seller", "buyer"]>>;
    accHolderName: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    ifsc: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    accountNo: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    bankName: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    gstin: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    upiId: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    billCounter: z.ZodOptional<z.ZodDefault<z.ZodNumber>>;
    barcodeCounter: z.ZodOptional<z.ZodDefault<z.ZodNumber>>;
}, z.ZodTypeAny, "passthrough">>;
/**
 * Schema used for validating Prisma update input. For internal use only.
 * @private
 */
export declare const CompanyPrismaUpdateSchema: z.ZodObject<{
    id: z.ZodOptional<z.ZodString>;
    name: z.ZodOptional<z.ZodString>;
    storecode: z.ZodOptional<z.ZodUnion<[z.ZodNumber, z.ZodRecord<z.ZodString, z.ZodUnknown>]>>;
    storeUniqueName: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    logo: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    description: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    shopifyStoreName: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    shopifyAccessToken: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    tiktokCipher: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    tiktokStoreName: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    tiktokAccessToken: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    tiktokAccessTokenExpireIn: z.ZodOptional<z.ZodUnion<[z.ZodOptional<z.ZodNullable<z.ZodNumber>>, z.ZodRecord<z.ZodString, z.ZodUnknown>]>>;
    tiktokRefreshToken: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    tiktokRefreshTokenExpireIn: z.ZodOptional<z.ZodUnion<[z.ZodOptional<z.ZodNullable<z.ZodNumber>>, z.ZodRecord<z.ZodString, z.ZodUnknown>]>>;
    images: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    isTaxIncluded: z.ZodOptional<z.ZodDefault<z.ZodBoolean>>;
    status: z.ZodOptional<z.ZodDefault<z.ZodBoolean>>;
    type: z.ZodOptional<z.ZodEnum<["seller", "buyer"]>>;
    accHolderName: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    ifsc: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    accountNo: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    bankName: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    gstin: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    upiId: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    billCounter: z.ZodOptional<z.ZodUnion<[z.ZodDefault<z.ZodNumber>, z.ZodRecord<z.ZodString, z.ZodUnknown>]>>;
    barcodeCounter: z.ZodOptional<z.ZodUnion<[z.ZodDefault<z.ZodNumber>, z.ZodRecord<z.ZodString, z.ZodUnknown>]>>;
}, "passthrough", z.ZodTypeAny, z.objectOutputType<{
    id: z.ZodOptional<z.ZodString>;
    name: z.ZodOptional<z.ZodString>;
    storecode: z.ZodOptional<z.ZodUnion<[z.ZodNumber, z.ZodRecord<z.ZodString, z.ZodUnknown>]>>;
    storeUniqueName: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    logo: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    description: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    shopifyStoreName: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    shopifyAccessToken: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    tiktokCipher: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    tiktokStoreName: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    tiktokAccessToken: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    tiktokAccessTokenExpireIn: z.ZodOptional<z.ZodUnion<[z.ZodOptional<z.ZodNullable<z.ZodNumber>>, z.ZodRecord<z.ZodString, z.ZodUnknown>]>>;
    tiktokRefreshToken: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    tiktokRefreshTokenExpireIn: z.ZodOptional<z.ZodUnion<[z.ZodOptional<z.ZodNullable<z.ZodNumber>>, z.ZodRecord<z.ZodString, z.ZodUnknown>]>>;
    images: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    isTaxIncluded: z.ZodOptional<z.ZodDefault<z.ZodBoolean>>;
    status: z.ZodOptional<z.ZodDefault<z.ZodBoolean>>;
    type: z.ZodOptional<z.ZodEnum<["seller", "buyer"]>>;
    accHolderName: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    ifsc: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    accountNo: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    bankName: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    gstin: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    upiId: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    billCounter: z.ZodOptional<z.ZodUnion<[z.ZodDefault<z.ZodNumber>, z.ZodRecord<z.ZodString, z.ZodUnknown>]>>;
    barcodeCounter: z.ZodOptional<z.ZodUnion<[z.ZodDefault<z.ZodNumber>, z.ZodRecord<z.ZodString, z.ZodUnknown>]>>;
}, z.ZodTypeAny, "passthrough">, z.objectInputType<{
    id: z.ZodOptional<z.ZodString>;
    name: z.ZodOptional<z.ZodString>;
    storecode: z.ZodOptional<z.ZodUnion<[z.ZodNumber, z.ZodRecord<z.ZodString, z.ZodUnknown>]>>;
    storeUniqueName: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    logo: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    description: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    shopifyStoreName: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    shopifyAccessToken: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    tiktokCipher: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    tiktokStoreName: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    tiktokAccessToken: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    tiktokAccessTokenExpireIn: z.ZodOptional<z.ZodUnion<[z.ZodOptional<z.ZodNullable<z.ZodNumber>>, z.ZodRecord<z.ZodString, z.ZodUnknown>]>>;
    tiktokRefreshToken: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    tiktokRefreshTokenExpireIn: z.ZodOptional<z.ZodUnion<[z.ZodOptional<z.ZodNullable<z.ZodNumber>>, z.ZodRecord<z.ZodString, z.ZodUnknown>]>>;
    images: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    isTaxIncluded: z.ZodOptional<z.ZodDefault<z.ZodBoolean>>;
    status: z.ZodOptional<z.ZodDefault<z.ZodBoolean>>;
    type: z.ZodOptional<z.ZodEnum<["seller", "buyer"]>>;
    accHolderName: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    ifsc: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    accountNo: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    bankName: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    gstin: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    upiId: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    billCounter: z.ZodOptional<z.ZodUnion<[z.ZodDefault<z.ZodNumber>, z.ZodRecord<z.ZodString, z.ZodUnknown>]>>;
    barcodeCounter: z.ZodOptional<z.ZodUnion<[z.ZodDefault<z.ZodNumber>, z.ZodRecord<z.ZodString, z.ZodUnknown>]>>;
}, z.ZodTypeAny, "passthrough">>;
/**
 * `Company` schema for create operations excluding foreign keys and relations.
 */
export declare const CompanyCreateScalarSchema: z.ZodObject<{
    id: z.ZodOptional<z.ZodString>;
    name: z.ZodString;
    storecode: z.ZodOptional<z.ZodNumber>;
    storeUniqueName: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    logo: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    description: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    shopifyStoreName: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    shopifyAccessToken: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    tiktokCipher: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    tiktokStoreName: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    tiktokAccessToken: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    tiktokAccessTokenExpireIn: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    tiktokRefreshToken: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    tiktokRefreshTokenExpireIn: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    images: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    isTaxIncluded: z.ZodOptional<z.ZodDefault<z.ZodBoolean>>;
    status: z.ZodOptional<z.ZodDefault<z.ZodBoolean>>;
    type: z.ZodEnum<["seller", "buyer"]>;
    accHolderName: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    ifsc: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    accountNo: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    bankName: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    gstin: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    upiId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    billCounter: z.ZodOptional<z.ZodDefault<z.ZodNumber>>;
    barcodeCounter: z.ZodOptional<z.ZodDefault<z.ZodNumber>>;
}, "strict", z.ZodTypeAny, {
    name: string;
    type: "seller" | "buyer";
    id?: string | undefined;
    storecode?: number | undefined;
    storeUniqueName?: string | null | undefined;
    logo?: string | null | undefined;
    description?: string | null | undefined;
    shopifyStoreName?: string | null | undefined;
    shopifyAccessToken?: string | null | undefined;
    tiktokCipher?: string | null | undefined;
    tiktokStoreName?: string | null | undefined;
    tiktokAccessToken?: string | null | undefined;
    tiktokAccessTokenExpireIn?: number | null | undefined;
    tiktokRefreshToken?: string | null | undefined;
    tiktokRefreshTokenExpireIn?: number | null | undefined;
    images?: string | null | undefined;
    isTaxIncluded?: boolean | undefined;
    status?: boolean | undefined;
    accHolderName?: string | null | undefined;
    ifsc?: string | null | undefined;
    accountNo?: string | null | undefined;
    bankName?: string | null | undefined;
    gstin?: string | null | undefined;
    upiId?: string | null | undefined;
    billCounter?: number | undefined;
    barcodeCounter?: number | undefined;
}, {
    name: string;
    type: "seller" | "buyer";
    id?: string | undefined;
    storecode?: number | undefined;
    storeUniqueName?: string | null | undefined;
    logo?: string | null | undefined;
    description?: string | null | undefined;
    shopifyStoreName?: string | null | undefined;
    shopifyAccessToken?: string | null | undefined;
    tiktokCipher?: string | null | undefined;
    tiktokStoreName?: string | null | undefined;
    tiktokAccessToken?: string | null | undefined;
    tiktokAccessTokenExpireIn?: number | null | undefined;
    tiktokRefreshToken?: string | null | undefined;
    tiktokRefreshTokenExpireIn?: number | null | undefined;
    images?: string | null | undefined;
    isTaxIncluded?: boolean | undefined;
    status?: boolean | undefined;
    accHolderName?: string | null | undefined;
    ifsc?: string | null | undefined;
    accountNo?: string | null | undefined;
    bankName?: string | null | undefined;
    gstin?: string | null | undefined;
    upiId?: string | null | undefined;
    billCounter?: number | undefined;
    barcodeCounter?: number | undefined;
}>;
/**
 * `Company` schema for create operations including scalar fields, foreign key fields, and validations.
 */
export declare const CompanyCreateSchema: z.ZodObject<{
    id: z.ZodOptional<z.ZodString>;
    name: z.ZodString;
    storecode: z.ZodOptional<z.ZodNumber>;
    storeUniqueName: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    logo: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    description: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    shopifyStoreName: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    shopifyAccessToken: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    tiktokCipher: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    tiktokStoreName: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    tiktokAccessToken: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    tiktokAccessTokenExpireIn: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    tiktokRefreshToken: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    tiktokRefreshTokenExpireIn: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    images: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    isTaxIncluded: z.ZodOptional<z.ZodDefault<z.ZodBoolean>>;
    status: z.ZodOptional<z.ZodDefault<z.ZodBoolean>>;
    type: z.ZodEnum<["seller", "buyer"]>;
    accHolderName: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    ifsc: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    accountNo: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    bankName: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    gstin: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    upiId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    billCounter: z.ZodOptional<z.ZodDefault<z.ZodNumber>>;
    barcodeCounter: z.ZodOptional<z.ZodDefault<z.ZodNumber>>;
}, "strict", z.ZodTypeAny, {
    name: string;
    type: "seller" | "buyer";
    id?: string | undefined;
    storecode?: number | undefined;
    storeUniqueName?: string | null | undefined;
    logo?: string | null | undefined;
    description?: string | null | undefined;
    shopifyStoreName?: string | null | undefined;
    shopifyAccessToken?: string | null | undefined;
    tiktokCipher?: string | null | undefined;
    tiktokStoreName?: string | null | undefined;
    tiktokAccessToken?: string | null | undefined;
    tiktokAccessTokenExpireIn?: number | null | undefined;
    tiktokRefreshToken?: string | null | undefined;
    tiktokRefreshTokenExpireIn?: number | null | undefined;
    images?: string | null | undefined;
    isTaxIncluded?: boolean | undefined;
    status?: boolean | undefined;
    accHolderName?: string | null | undefined;
    ifsc?: string | null | undefined;
    accountNo?: string | null | undefined;
    bankName?: string | null | undefined;
    gstin?: string | null | undefined;
    upiId?: string | null | undefined;
    billCounter?: number | undefined;
    barcodeCounter?: number | undefined;
}, {
    name: string;
    type: "seller" | "buyer";
    id?: string | undefined;
    storecode?: number | undefined;
    storeUniqueName?: string | null | undefined;
    logo?: string | null | undefined;
    description?: string | null | undefined;
    shopifyStoreName?: string | null | undefined;
    shopifyAccessToken?: string | null | undefined;
    tiktokCipher?: string | null | undefined;
    tiktokStoreName?: string | null | undefined;
    tiktokAccessToken?: string | null | undefined;
    tiktokAccessTokenExpireIn?: number | null | undefined;
    tiktokRefreshToken?: string | null | undefined;
    tiktokRefreshTokenExpireIn?: number | null | undefined;
    images?: string | null | undefined;
    isTaxIncluded?: boolean | undefined;
    status?: boolean | undefined;
    accHolderName?: string | null | undefined;
    ifsc?: string | null | undefined;
    accountNo?: string | null | undefined;
    bankName?: string | null | undefined;
    gstin?: string | null | undefined;
    upiId?: string | null | undefined;
    billCounter?: number | undefined;
    barcodeCounter?: number | undefined;
}>;
/**
 * `Company` schema for update operations excluding foreign keys and relations.
 */
export declare const CompanyUpdateScalarSchema: z.ZodObject<{
    id: z.ZodOptional<z.ZodString>;
    name: z.ZodOptional<z.ZodString>;
    storecode: z.ZodOptional<z.ZodNumber>;
    storeUniqueName: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    logo: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    description: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    shopifyStoreName: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    shopifyAccessToken: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    tiktokCipher: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    tiktokStoreName: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    tiktokAccessToken: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    tiktokAccessTokenExpireIn: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodNumber>>>;
    tiktokRefreshToken: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    tiktokRefreshTokenExpireIn: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodNumber>>>;
    images: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    isTaxIncluded: z.ZodOptional<z.ZodDefault<z.ZodBoolean>>;
    status: z.ZodOptional<z.ZodDefault<z.ZodBoolean>>;
    type: z.ZodOptional<z.ZodEnum<["seller", "buyer"]>>;
    accHolderName: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    ifsc: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    accountNo: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    bankName: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    gstin: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    upiId: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    billCounter: z.ZodOptional<z.ZodDefault<z.ZodNumber>>;
    barcodeCounter: z.ZodOptional<z.ZodDefault<z.ZodNumber>>;
}, "strict", z.ZodTypeAny, {
    id?: string | undefined;
    name?: string | undefined;
    storecode?: number | undefined;
    storeUniqueName?: string | null | undefined;
    logo?: string | null | undefined;
    description?: string | null | undefined;
    shopifyStoreName?: string | null | undefined;
    shopifyAccessToken?: string | null | undefined;
    tiktokCipher?: string | null | undefined;
    tiktokStoreName?: string | null | undefined;
    tiktokAccessToken?: string | null | undefined;
    tiktokAccessTokenExpireIn?: number | null | undefined;
    tiktokRefreshToken?: string | null | undefined;
    tiktokRefreshTokenExpireIn?: number | null | undefined;
    images?: string | null | undefined;
    isTaxIncluded?: boolean | undefined;
    status?: boolean | undefined;
    type?: "seller" | "buyer" | undefined;
    accHolderName?: string | null | undefined;
    ifsc?: string | null | undefined;
    accountNo?: string | null | undefined;
    bankName?: string | null | undefined;
    gstin?: string | null | undefined;
    upiId?: string | null | undefined;
    billCounter?: number | undefined;
    barcodeCounter?: number | undefined;
}, {
    id?: string | undefined;
    name?: string | undefined;
    storecode?: number | undefined;
    storeUniqueName?: string | null | undefined;
    logo?: string | null | undefined;
    description?: string | null | undefined;
    shopifyStoreName?: string | null | undefined;
    shopifyAccessToken?: string | null | undefined;
    tiktokCipher?: string | null | undefined;
    tiktokStoreName?: string | null | undefined;
    tiktokAccessToken?: string | null | undefined;
    tiktokAccessTokenExpireIn?: number | null | undefined;
    tiktokRefreshToken?: string | null | undefined;
    tiktokRefreshTokenExpireIn?: number | null | undefined;
    images?: string | null | undefined;
    isTaxIncluded?: boolean | undefined;
    status?: boolean | undefined;
    type?: "seller" | "buyer" | undefined;
    accHolderName?: string | null | undefined;
    ifsc?: string | null | undefined;
    accountNo?: string | null | undefined;
    bankName?: string | null | undefined;
    gstin?: string | null | undefined;
    upiId?: string | null | undefined;
    billCounter?: number | undefined;
    barcodeCounter?: number | undefined;
}>;
/**
 * `Company` schema for update operations including scalar fields, foreign key fields, and validations.
 */
export declare const CompanyUpdateSchema: z.ZodObject<{
    id: z.ZodOptional<z.ZodString>;
    name: z.ZodOptional<z.ZodString>;
    storecode: z.ZodOptional<z.ZodNumber>;
    storeUniqueName: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    logo: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    description: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    shopifyStoreName: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    shopifyAccessToken: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    tiktokCipher: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    tiktokStoreName: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    tiktokAccessToken: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    tiktokAccessTokenExpireIn: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodNumber>>>;
    tiktokRefreshToken: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    tiktokRefreshTokenExpireIn: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodNumber>>>;
    images: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    isTaxIncluded: z.ZodOptional<z.ZodDefault<z.ZodBoolean>>;
    status: z.ZodOptional<z.ZodDefault<z.ZodBoolean>>;
    type: z.ZodOptional<z.ZodEnum<["seller", "buyer"]>>;
    accHolderName: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    ifsc: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    accountNo: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    bankName: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    gstin: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    upiId: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    billCounter: z.ZodOptional<z.ZodDefault<z.ZodNumber>>;
    barcodeCounter: z.ZodOptional<z.ZodDefault<z.ZodNumber>>;
}, "strict", z.ZodTypeAny, {
    id?: string | undefined;
    name?: string | undefined;
    storecode?: number | undefined;
    storeUniqueName?: string | null | undefined;
    logo?: string | null | undefined;
    description?: string | null | undefined;
    shopifyStoreName?: string | null | undefined;
    shopifyAccessToken?: string | null | undefined;
    tiktokCipher?: string | null | undefined;
    tiktokStoreName?: string | null | undefined;
    tiktokAccessToken?: string | null | undefined;
    tiktokAccessTokenExpireIn?: number | null | undefined;
    tiktokRefreshToken?: string | null | undefined;
    tiktokRefreshTokenExpireIn?: number | null | undefined;
    images?: string | null | undefined;
    isTaxIncluded?: boolean | undefined;
    status?: boolean | undefined;
    type?: "seller" | "buyer" | undefined;
    accHolderName?: string | null | undefined;
    ifsc?: string | null | undefined;
    accountNo?: string | null | undefined;
    bankName?: string | null | undefined;
    gstin?: string | null | undefined;
    upiId?: string | null | undefined;
    billCounter?: number | undefined;
    barcodeCounter?: number | undefined;
}, {
    id?: string | undefined;
    name?: string | undefined;
    storecode?: number | undefined;
    storeUniqueName?: string | null | undefined;
    logo?: string | null | undefined;
    description?: string | null | undefined;
    shopifyStoreName?: string | null | undefined;
    shopifyAccessToken?: string | null | undefined;
    tiktokCipher?: string | null | undefined;
    tiktokStoreName?: string | null | undefined;
    tiktokAccessToken?: string | null | undefined;
    tiktokAccessTokenExpireIn?: number | null | undefined;
    tiktokRefreshToken?: string | null | undefined;
    tiktokRefreshTokenExpireIn?: number | null | undefined;
    images?: string | null | undefined;
    isTaxIncluded?: boolean | undefined;
    status?: boolean | undefined;
    type?: "seller" | "buyer" | undefined;
    accHolderName?: string | null | undefined;
    ifsc?: string | null | undefined;
    accountNo?: string | null | undefined;
    bankName?: string | null | undefined;
    gstin?: string | null | undefined;
    upiId?: string | null | undefined;
    billCounter?: number | undefined;
    barcodeCounter?: number | undefined;
}>;
