const unitAliases: Record<string, string> = {
  No: 'Nos',
  Piece: 'Pieces',
  Each: 'Pieces',
  Pair: 'Pairs',
  Dozen: 'Dozens',
  Set: 'Sets',
  Pack: 'Packs',
  Packet: 'Packets',
  Box: 'Boxes',
  Bundle: 'Bundles',
  Carton: 'Cartons',
  Case: 'Cases',
  Crate: 'Crates',
  Tray: 'Trays',
  Sack: 'Sacks',
  Bag: 'Bags',
  Kg: 'Kgs',
  'Kg(s)': 'Kgs',
  Gram: 'Grams',
  Gm: 'Gms',
  Mg: 'Mgs',
  Tonne: 'Tonnes',
  Quintal: 'Quintals',
  Litre: 'Litres',
  Liter: 'Liters',
  Millilitre: 'Millilitres',
  Ml: 'Mls',
  Gallon: 'Gallons',
  Pint: 'Pints',
  Quart: 'Quarts',
  Cup: 'Cups',
  Sqft: 'Sqfts',
  'Sq yd': 'Sq yds',
  'Sq in': 'Sq ins',
  'Sq cm': 'Sq cms',
  'Sq mm': 'Sq mms',
  Km: 'Kms',
  Meter: 'Meters',
  Metre: 'Metres',
  Centimeter: 'Centimeters',
  Millimeter: 'Millimeters',
  Foot: 'Feet',
  Inch: 'Inches',
  Yard: 'Yards',
  Drum: 'Drums',
  Roll: 'Rolls',
  Sheet: 'Sheets',
  Ream: 'Reams',
  Strip: 'Strips',
  Tube: 'Tubes',
  Bottle: 'Bottles',
  Can: 'Cans',
  Jar: 'Jars',
  Tin: 'Tins',
  Pouch: 'Pouches',
  'Bundle of 10': 'Bundles of 10',
  'Per Day': 'Per Days',
  'Per Week': 'Per Weeks',
  'Per Month': 'Per Months',
  'Per Hour': 'Per Hours',
  'Per Piece': 'Per Pieces',
  Day: 'Days',
  Week: 'Weeks',
  Month: 'Months',
  Hour: 'Hours',
}

export const billingUnitOptions = [
  'Nos',
  'Pieces',
  'Pcs',
  'Pairs',
  'Dozens',
  'Sets',
  'Packs',
  'Packets',
  'Boxes',
  'Bundles',
  'Cartons',
  'Cases',
  'Crates',
  'Trays',
  'Sacks',
  'Bags',
  'Kgs',
  'Grams',
  'Gms',
  'Mgs',
  'Tonnes',
  'Quintals',
  'Brass',
  'Litres',
  'Liters',
  'Millilitres',
  'Mls',
  'Gallons',
  'Pints',
  'Quarts',
  'Cups',
  'Sqfts',
  'Sq m',
  'Sq yds',
  'Sq ins',
  'Sq cms',
  'Sq mms',
  'Kms',
  'Meters',
  'Metres',
  'Centimeters',
  'Millimeters',
  'Feet',
  'Inches',
  'Yards',
  'Lengths',
  'Drums',
  'Rolls',
  'Sheets',
  'Reams',
  'Strips',
  'Tubes',
  'Bottles',
  'Cans',
  'Jars',
  'Tins',
  'Pouches',
  'Bag of 50',
  'Bundles of 10',
  'Per Days',
  'Per Weeks',
  'Per Months',
  'Per Hours',
  'Per Pieces',
  'Days',
  'Weeks',
  'Months',
  'Hours',
]

export const billingUnitSelectOptions = ['All', ...billingUnitOptions]

export const normalizeBillingUnits = (units: unknown) => {
  const values = Array.isArray(units)
    ? units
    : typeof units === 'string' && units.length > 0
      ? [units]
      : []

  const normalized = values
    .map((unit) => unitAliases[unit] || unit)
    .filter((unit): unit is string => billingUnitOptions.includes(unit))

  return normalized.length ? [...new Set(normalized)] : ['Nos']
}

